### ISSUE TITLE
Error in bigdata rdf store PhysicalAddressResolutionException

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1196]
Big data server is not available to matchers, even after redeploy the following Exception in the log pops up: 

WARN : RWStore.java:6410: WriteCacheDebug: 964154560 - No WriteCache debug info
WARN : FixedAllocator.java:184: Physical address 964154560 not accessible for Allocator of size 64
ERROR: ASTRangeCountOptimizer.java:129: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
ERROR: BigdataRDFServlet.java:189: cause=java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670, query=SPARQL-QUERY: queryStr=SELECT  ?graphUri ?nodeUri
WHERE
  { GRAPH ?graphUri
      { ?nodeUri  <http://purl.org/webofneeds/model#hasUriPrefixSpecification>  ?c }
  }

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sail.webapp.QueryServlet.doSparqlQuery(QueryServlet.java:517)
        at com.bigdata.rdf.sail.webapp.QueryServlet.doGet(QueryServlet.java:206)
        at com.bigdata.rdf.sail.webapp.RESTServlet.doGet(RESTServlet.java:210)
        at com.bigdata.rdf.sail.webapp.MultiTenancyServlet.doGet(MultiTenancyServlet.java:220)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:710)
        at com.bigdata.rdf.sail.webapp.QueryServlet$SparqlQueryTask.call(QueryServlet.java:534)
        at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:67)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.bigdata.rdf.task.AbstractApiTask.submitApiTask(AbstractApiTask.java:315)
        at com.bigdata.rdf.sail.webapp.BigdataServlet.submitApiTask(BigdataServlet.java:220)
        ... 26 more
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:1294)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask.call(BigdataRDFContext.java:504)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        ... 1 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer.attachRangeCounts(ASTRangeCountOptimizer.java:140)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer.optimizeJoinGroup(ASTRangeCountOptimizer.java:77)
        at com.bigdata.rdf.sparql.ast.optimizers.AbstractJoinGroupOptimizer.optimize(AbstractJoinGroupOptimizer.java:157)
        at com.bigdata.rdf.sparql.ast.optimizers.AbstractJoinGroupOptimizer.optimize(AbstractJoinGroupOptimizer.java:97)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTOptimizerList.optimize(ASTOptimizerList.java:104)
        at com.bigdata.rdf.sparql.ast.eval.AST2BOpUtility.convert(AST2BOpUtility.java:222)
        at com.bigdata.rdf.sparql.ast.eval.ASTEvalHelper.evaluateTupleQuery(ASTEvalHelper.java:244)
        at com.bigdata.rdf.sail.BigdataSailTupleQuery.evaluate(BigdataSailTupleQuery.java:93)
        at com.bigdata.rdf.sail.BigdataSailTupleQuery.evaluate(BigdataSailTupleQuery.java:75)
        at org.openrdf.repository.sail.SailTupleQuery.evaluate(SailTupleQuery.java:75)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$TupleQueryTask.doQuery(BigdataRDFContext.java:1405)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask$SparqlRestApiTask.call(BigdataRDFContext.java:1238)
        at com.bigdata.rdf.sail.webapp.BigdataRDFContext$AbstractQueryTask$SparqlRestApiTask.call(BigdataRDFContext.java:1188)
        at com.bigdata.rdf.task.ApiTaskForIndexManager.call(ApiTaskForIndexManager.java:67)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.bigdata.rdf.task.AbstractApiTask.submitApiTask(AbstractApiTask.java:315)
        ... 6 more
Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer.attachRangeCounts(ASTRangeCountOptimizer.java:124)
        ... 21 more
Caused by: java.lang.IllegalArgumentException: Unable to read data: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at com.bigdata.rwstore.RWStore.getData(RWStore.java:2186)
        at com.bigdata.rwstore.RWStore.getData(RWStore.java:1994)
        at com.bigdata.rwstore.RWStore.getData(RWStore.java:2038)
        at com.bigdata.rwstore.RWStore.getData(RWStore.java:1946)
        at com.bigdata.journal.RWStrategy.readFromLocalStore(RWStrategy.java:733)
        at com.bigdata.journal.RWStrategy.read(RWStrategy.java:156)
        at com.bigdata.journal.AbstractJournal.read(AbstractJournal.java:4255)
        at com.bigdata.btree.AbstractBTree.readNodeOrLeaf(AbstractBTree.java:4013)
        at com.bigdata.btree.Node._getChild(Node.java:2728)
        at com.bigdata.btree.AbstractBTree$1.compute(AbstractBTree.java:363)
        at com.bigdata.btree.AbstractBTree$1.compute(AbstractBTree.java:346)
        at com.bigdata.util.concurrent.Memoizer$1.call(Memoizer.java:77)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.bigdata.util.concurrent.Memoizer.compute(Memoizer.java:92)
        at com.bigdata.btree.AbstractBTree.loadChild(AbstractBTree.java:527)
        at com.bigdata.btree.Node.getChild(Node.java:2629)
        at com.bigdata.btree.Node.indexOf(Node.java:972)
        at com.bigdata.btree.AbstractBTree.rangeCount(AbstractBTree.java:2626)
        at com.bigdata.relation.accesspath.AccessPath.historicalRangeCount(AccessPath.java:1418)
        at com.bigdata.relation.accesspath.AccessPath.rangeCount(AccessPath.java:1386)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer.estimateCardinalities(ASTRangeCountOptimizer.java:201)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer.estimateCardinality(ASTRangeCountOptimizer.java:191)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer$RangeCountTask.call(ASTRangeCountOptimizer.java:171)
        at com.bigdata.rdf.sparql.ast.optimizers.ASTRangeCountOptimizer$RangeCountTask.call(ASTRangeCountOptimizer.java:154)
        ... 4 more
Caused by: com.bigdata.rwstore.PhysicalAddressResolutionException: Address did not resolve to physical address: -1827670
        at com.bigdata.rwstore.RWStore.getData(RWStore.java:2096)
        ... 27 more

**Comment by heikofriedrich** [comment]
Seems to be some error in the bigdata store. To resolve it i deleted all the data of the rdf store on the hard drive and redeployed the application. The matching service then anyways recrawls all needs and fills the rdf store again.
