### ISSUE TITLE
Wonnode log gets spammed by wrong error handling

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1237]
on the master node the wonnode log gets spammed with a lot of log messages. there seems to be some kind of loop in the error handling, the log is about 150 GB big:

`29.9.17 14:57:00.342 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] WARN  o.a.c.s.spi.TransactionErrorHandler - Cannot determine current route from Exchange with id: ID-55c294ef014f-37773-1506696823415-0-3801, will fallback and use first error handler.
29.9.17 14:57:00.394 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] WARN  o.a.c.s.spi.TransactionErrorHandler - Cannot determine current route from Exchange with id: ID-55c294ef014f-37773-1506696823415-0-3806, will fallback and use first error handler.
29.9.17 14:57:00.426 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.437 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.452 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.453 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.458 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.458 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.463 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.466 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.466 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.467 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.467 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.472 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.472 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.478 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.479 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.479 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.487 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.492 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.496 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.497 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.499 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.499 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.499 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.500 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.503 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.514 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.515 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.516 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.524 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.524 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. T
he previous and the new exception will be logged in the following.
29.9.17 14:57:00.527 [Camel (wonNodeCamel) thread #7 - seda://OwnerProtocolOut] WARN  o.a.c.s.spi.TransactionErrorHandler - Cannot determine current route from Exchange with id: ID-55c294ef014f-37773-1506696823415-0-3811, will fallback and use first error handler.
29.9.17 14:57:00.529 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.535 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.540 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.540 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.545 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.545 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.546 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.551 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.555 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.557 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.559 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.560 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.564 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.565 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.575 [Camel (wonNodeCamel) thread #6 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3806 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.640 [Camel (wonNodeCamel) thread #7 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - Exception occurred while trying to handle previously thrown exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3811 using: [Channel[sendTo(Endpoint[direct://sendFailureResponse])]]. The previous and the new exception will be logged in the following.
29.9.17 14:57:00.652 [Camel (wonNodeCamel) thread #5 - seda://OwnerProtocolOut] WARN  o.a.c.s.spi.TransactionErrorHandler - Cannot determine current route from Exchange with id: ID-55c294ef014f-37773-1506696823415-0-3816, will fallback and use first error handler.
29.9.17 14:57:00.711 [Camel (wonNodeCamel) thread #9 - seda://OwnerProtocolOut] ERROR o.a.c.p.FatalFallbackErrorHandler - \--> Previous exception on exchangeId: ID-55c294ef014f-37773-1506696823415-0-3801
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[Message: <https://satvm02.researchstudio.at/won/resource/event/qh9aqlo1qtqxj17nkzjv#envelope-vu65-sig> {
    <https://satvm02.researchstudio.at/won/resource/event/qh9aqlo1qtqxj17nkzjv#envelope-vu65-sig>
            a       <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#Signature> ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasSignatureValue>
                    "MGQCMGd5TRrOFA/Cs2R0WG111XIUuwUIBr8nP6/eWFRO9VhoEakxNeSjnZzG6NCkE5wUBAIwQleVM/Qzmx1pizJYDhQjgNV4qvKGGbmuv0PByo+5c5yUm+LcnrlBSVKnAwhl9Wle" ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasVerificationCertificate>
                    <https://satvm02.researchstudio.at/won/resource> ;
            <http://purl.org/webofneeds/message#hasHash>
                    "ALC0eb3KUuYAiBI0kP5AWUc7ngrIUnNVlgXBpZYBmLSVs6ILjhv1pYgmr24qmYENWb5Np1Zf4MHZnumHZs1mal0RvEFYTGk2wY0D0dpQyPJxRMjEDrIx0VZfdj0obLm5eMdpchin6L1hvp3LTlBY7rKgxfDtMwWraTbnVvm03yc3" ;
            <http://p... [Body clipped after 1000 chars, total length is 9011]]
        at org.apache.camel.util.ObjectHelper.wrapCamelExecutionException(ObjectHelper.java:1360) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.impl.DefaultExchange.setException(DefaultExchange.java:283) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:114) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:99) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:56) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.FatalFallbackErrorHandler.process(FatalFallbackErrorHandler.java:42) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.deliverToFailureProcessor(RedeliveryErrorHandler.java:839) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:337) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:99) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:56) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.FatalFallbackErrorHandler.process(FatalFallbackErrorHandler.java:42) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.deliverToFailureProcessor(RedeliveryErrorHandler.java:839) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:337) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:99) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:56) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.FatalFallbackErrorHandler.process(FatalFallbackErrorHandler.java:42) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.deliverToFailureProcessor(RedeliveryErrorHandler.java:839) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:337) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.processByErrorHandler(TransactionErrorHandler.java:218) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.spring.spi.TransactionErrorHandler.process(TransactionErrorHandler.java:99) ~[camel-spring-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:166) ~[camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:56) ~[camel-core-2.12.1.jar:2.12.1]
`
....

**Comment by heikofriedrich** [comment]
first action: created docker daemon.json config file in /etc/docker/ on satvm01, satvm02, satvm03, satvm05 to achieve log rotation in such cases

**Comment by heikofriedrich** [comment]
@fkleedorfer do you see what is the problem here? Is there an exception in our application that gets handled by camel which produces another exception which in turn produces a loop?

**Comment by heikofriedrich** [comment]
tried with better error handling with commit #c3f5e7a

**Comment by heikofriedrich** [comment]
when the log flooding begins on a wonnode then it seems also not possible to create new needs anymore

**Comment by fkleedorfer** [comment]
Tried with a different camel route config - adding .handled(true) and doing only 2 redelivery attempts, and logging when it happens
