### ISSUE TITLE
Matcher cannot send messages to wonnode

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1250]
I accidently deleted all data on the master environment, while deploying the application (from integration-test source to master by redirecting the jenkins). After that the matcher couldnt send matches to the wonnode anymore. And the message sending process times out after 20 seconds.

```[WARN] [10/11/2017 12:12:36.047] [ClusterSystem-akka.actor.default-dispatcher-17] [akka://ClusterSystem/user/WonNodeControllerActor] Actor encountered error: akka.camel.AkkaCamelException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-2ad543f81e33-36242-1507723816020-0-99 not received on destination: temp-queue://ID:2ad543f81e33-45169-1507723817677-17:1:1. Exchange[]
11.10.17 12:12:36.048 [ClusterSystem-akka.actor.default-dispatcher-5] INFO  o.a.c.impl.DefaultShutdownStrategy - Starting to graceful shutdown 1 routes (timeout 300 seconds)
[ERROR] [10/11/2017 12:12:36.047] [ClusterSystem-akka.actor.default-dispatcher-17] [akka://ClusterSystem/user/WonNodeControllerActor] The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-2ad543f81e33-36242-1507723816020-0-99 not received on destination: temp-queue://ID:2ad543f81e33-45169-1507723817677-17:1:1. Exchange[]
akka.camel.AkkaCamelException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-2ad543f81e33-36242-1507723816020-0-99 not received on destination: temp-queue://ID:2ad543f81e33-45169-1507723817677-17:1:1. Exchange[]
        at akka.camel.ProducerSupport$$anonfun$produce$1.applyOrElse(Producer.scala:73)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.camel.javaapi.UntypedProducerActor.onReceive(UntypedProducerActor.scala:49)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.camel.ExchangeTimedOutException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-2ad543f81e33-36242-1507723816020-0-99 not received on destination: temp-queue://ID:2ad543f81e33-45169-1507723817677-17:1:1. Exchange[]
        at org.apache.camel.component.jms.reply.ReplyManagerSupport.processReply(ReplyManagerSupport.java:170)
        at org.apache.camel.component.jms.reply.TemporaryQueueReplyHandler.onTimeout(TemporaryQueueReplyHandler.java:62)
        at org.apache.camel.component.jms.reply.CorrelationTimeoutMap$1.run(CorrelationTimeoutMap.java:60)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)```

**Comment by heikofriedrich** [comment]
Problem looked similar than #637 but this this restart of the node didnt fix the problem

**Comment by heikofriedrich** [comment]
After another rebuild and deploy it is working fine again
