### ISSUE TITLE
jena sparql stackoverflow exception in matcher service

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1308]
Matcher on matchat.org runs into stackoverflow error:

````
[WARN] [11/02/2017 05:48:13.791] [ClusterSystem-akka.actor.default-dispatcher-422] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor] Actor encountered error: org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
[WARN] [11/02/2017 05:48:13.792] [ClusterSystem-akka.actor.default-dispatcher-434] [akka://ClusterSystem/user/WonNodeControllerActor] Actor encountered error: org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
2.11.17 05:48:13.795 [ClusterSystem-akka.actor.default-dispatcher-388] INFO  o.a.c.impl.DefaultShutdownStrategy - Starting to graceful shutdown 1 routes (timeout 300 seconds)
[ERROR] [11/02/2017 05:48:13.792] [ClusterSystem-akka.actor.default-dispatcher-434] [akka://ClusterSystem/user/WonNodeControllerActor] java.lang.StackOverflowError
org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
        at org.apache.jena.sparql.lang.ParserSPARQL11Update._parse(ParserSPARQL11Update.java:79)
        at org.apache.jena.sparql.lang.ParserSPARQL11Update.parse$(ParserSPARQL11Update.java:40)
        at org.apache.jena.sparql.lang.UpdateParser.parse(UpdateParser.java:39)
        at org.apache.jena.update.UpdateFactory.make(UpdateFactory.java:87)
        at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:78)
        at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:56)
        at org.apache.jena.update.UpdateFactory.create(UpdateFactory.java:46)
        at won.matcher.service.common.service.sparql.SparqlService.executeUpdateQuery(SparqlService.java:150)
        at won.matcher.service.common.service.sparql.SparqlService.updateNamedGraphsOfDataset(SparqlService.java:96)
        at won.matcher.service.crawler.actor.WorkerCrawlerActor.onReceive(WorkerCrawlerActor.java:136)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.jena.ext.com.google.common.util.concurrent.ExecutionError: java.lang.StackOverflowError
        at org.apache.jena.ext.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        at org.apache.jena.ext.com.google.common.cache.LocalCache.get(LocalCache.java:3937)
        at org.apache.jena.ext.com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
        at org.apache.jena.atlas.lib.cache.CacheGuava.getOrFill(CacheGuava.java:58)
        at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolveSilentCache(IRIResolver.java:473)
        at org.apache.jena.riot.system.IRIResolver$IRIResolverNormal.resolveSilent(IRIResolver.java:457)
        at org.apache.jena.sparql.lang.ParserBase.resolveIRI(ParserBase.java:259)
        at org.apache.jena.sparql.lang.ParserBase.resolveQuotedIRI(ParserBase.java:243)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.IRIREF(SPARQLParser11.java:4893)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.iri(SPARQLParser11.java:4836)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GraphTerm(SPARQLParser11.java:3360)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.VarOrTerm(SPARQLParser11.java:3277)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.GraphNode(SPARQLParser11.java:3191)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.Object(SPARQLParser11.java:2576)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.ObjectList(SPARQLParser11.java:2557)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.PropertyListNotEmpty(SPARQLParser11.java:2503)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesSameSubject(SPARQLParser11.java:2468)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1619)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)
        at org.apache.jena.sparql.lang.sparql_11.SPARQLParser11.TriplesTemplate(SPARQLParser11.java:1649)

````

before the error several resumeafter queries occur in the log for sucessful crawling: 

````
[INFO] [11/02/2017 05:53:46.779] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-301] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=8280595646906669000
[INFO] [11/02/2017 05:53:47.016] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=4308563535166336000
[INFO] [11/02/2017 05:53:47.059] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-301] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=4308563535166336000
[INFO] [11/02/2017 05:53:47.441] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=4778791697731465000
[INFO] [11/02/2017 05:53:47.529] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-301] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=4778791697731465000
[INFO] [11/02/2017 05:53:47.742] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=7736855360608997000
[INFO] [11/02/2017 05:53:47.753] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=7736855360608997000
[INFO] [11/02/2017 05:53:48.032] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=3109909366259468300
[INFO] [11/02/2017 05:53:48.042] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=3109909366259468300
[INFO] [11/02/2017 05:53:48.325] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=5448940639422607000
[INFO] [11/02/2017 05:53:48.348] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=5448940639422607000
[INFO] [11/02/2017 05:53:48.642] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=7972149867612647000
[INFO] [11/02/2017 05:53:48.680] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=7972149867612647000
[INFO] [11/02/2017 05:53:48.940] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=5791869798714558000
[INFO] [11/02/2017 05:53:48.949] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=5791869798714558000
[INFO] [11/02/2017 05:53:49.246] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=5455759260540632000
[INFO] [11/02/2017 05:53:49.256] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=5455759260540632000
[INFO] [11/02/2017 05:53:49.522] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=8679800429490113000
[INFO] [11/02/2017 05:53:49.651] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=8679800429490113000
[INFO] [11/02/2017 05:53:49.908] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=3344794514888529000
[INFO] [11/02/2017 05:53:49.975] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$a] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=3344794514888529000
[INFO] [11/02/2017 05:53:50.201] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-379] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need?resumeafter=8405925772178387000
[INFO] [11/02/2017 05:53:50.252] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-304] [akka://Cluste^C
root@satvm01:~# docker logs livesatvm01_matcher_service_1 | less
[INFO] [11/02/2017 18:49:26.503] [ClusterSystem-BalancingPool-/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter-488] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor/CrawlingRouter/$b] Crawling done for URI https://node.matchat.org/won/resource/need/?resumeafter=2932171877729042400
[WARN] [11/02/2017 18:49:27.416] [ClusterSystem-akka.actor.default-dispatcher-457] [akka://ClusterSystem/user/WonNodeControllerActor/MasterCrawlerActor] Actor encountered error: org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
[WARN] [11/02/2017 18:49:27.416] [ClusterSystem-akka.actor.default-dispatcher-457] [akka://ClusterSystem/user/WonNodeControllerActor] Actor encountered error: org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
2.11.17 18:49:27.416 [ClusterSystem-akka.actor.default-dispatcher-472] INFO  o.a.c.impl.DefaultShutdownStrategy - Starting to graceful shutdown 1 routes (timeout 300 seconds)
[ERROR] [11/02/2017 18:49:27.416] [ClusterSystem-akka.actor.default-dispatcher-508] [akka://ClusterSystem/user/WonNodeControllerActor] java.lang.StackOverflowError
org.apache.jena.query.QueryParseException: java.lang.StackOverflowError
        at org.apache.jena.sparql.lang.ParserSPARQL11Update._parse(ParserSPARQL11Update.java:79)

````

**Comment by heikofriedrich** [comment]
restarted the service and set logging to debug level, to get a chance to see if there is a problem with the sparql query that may have caused the problem

**Comment by fkleedorfer** [comment]
cannot reproduce
