### ISSUE TITLE
First deployment of new jenkins job fails

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1356]
Jenkins log:
````
[INFO] > won-owner-webapp@0.2.0 clean /var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp
[INFO] > gulp clean
[INFO] 
[ERROR] fs.js:862
[ERROR]   return binding.readdir(pathModule._makeLong(path), options.encoding);
[ERROR]                  ^
[ERROR] 
[ERROR] Error: ENOENT: no such file or directory, scandir '/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/vendor'
[ERROR]     at Object.fs.readdirSync (fs.js:862:18)
[ERROR]     at Object.getInstalledBinaries (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/extensions.js:121:13)
[ERROR]     at foundBinariesList (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/errors.js:20:15)
[ERROR]     at foundBinaries (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/errors.js:15:5)
[ERROR]     at Object.module.exports.missingBinary (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/errors.js:45:5)
[ERROR]     at module.exports (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/binding.js:15:30)
[ERROR]     at Object.<anonymous> (/var/lib/jenkins/workspace/webofneeds-uki/webofneeds/won-owner-webapp/src/main/webapp/node_modules/node-sass/lib/index.js:14:35)
[ERROR]     at Module._compile (module.js:573:32)
[ERROR]     at Object.Module._extensions..js (module.js:582:10)
[ERROR]     at Module.load (module.js:490:32)
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! won-owner-webapp@0.2.0 clean: `gulp clean`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the won-owner-webapp@0.2.0 clean script 'gulp clean'.
[ERROR] npm ERR! Make sure you have the latest version of node.js and npm installed.
[ERROR] npm ERR! If you do, this is most likely a problem with the won-owner-webapp package,
[ERROR] npm ERR! not with npm itself.
[ERROR] npm ERR! Tell the author that this fails on your system:
[ERROR] npm ERR!     gulp clean
[ERROR] npm ERR! You can get information on how to open an issue for this project with:
[ERROR] npm ERR!     npm bugs won-owner-webapp
[ERROR] npm ERR! Or if that isn't available, you can get their info via:
[ERROR] npm ERR!     npm owner ls won-owner-webapp
[ERROR] npm ERR! There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /var/lib/jenkins/.npm/_logs/2018-01-02T15_21_05_753Z-debug.log

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Web of Needs Main .................................. SUCCESS [  0.566 s]
[INFO] Core ............................................... SUCCESS [  4.544 s]
[INFO] Facet Modules ...................................... SUCCESS [  0.105 s]
[INFO] Facets: Transactions ............................... SUCCESS [  1.198 s]
[INFO] Cryptography ....................................... SUCCESS [  2.641 s]
[INFO] Node ............................................... SUCCESS [  2.814 s]
[INFO] Node Webapp ........................................ SUCCESS [  4.673 s]
[INFO] Owner .............................................. SUCCESS [  1.995 s]
[INFO] Matcher Client ..................................... SUCCESS [  1.469 s]
[INFO] Utilities .......................................... SUCCESS [  0.103 s]
[INFO] Utilities-Mail ..................................... SUCCESS [  1.115 s]
[INFO] Owner Webapp ....................................... FAILURE [  0.901 s]
[INFO] Matcher Utils ...................................... SKIPPED
[INFO] Matcher Service .................................... SKIPPED
[INFO] Bot ................................................ SKIPPED
[INFO] won-matcher-solr ................................... SKIPPED
[INFO] Matcher-Rescal ..................................... SKIPPED
[INFO] Ontology Validator ................................. SKIPPED
[INFO] Utilities-Import ................................... SKIPPED
[INFO] Utilities-Crawling ................................. SKIPPED
[INFO] Utilities-Goals .................................... SKIPPED
[INFO] Vocabulary ......................................... SKIPPED
[INFO] Docker ............................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 27.531 s
[INFO] Finished at: 2018-01-02T16:21:07+01:00
[INFO] Final Memory: 181M/1121M
[INFO] ------------------------------------------------------------------------
````

**Comment by heikofriedrich** [comment]
=> solution: remove "clean" command from the first maven jenkins execution and just do "package". If it runs through, clean can be added before again. 
see also #949
