### ISSUE TITLE
Certificate key error when starting up owner application

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#1360]
Error in owner log when starting up: 
````
Some of your private key files are encrypted for security reasons.
In order to read them you have to provide the pass phrases.
Enter password :
Some of your private key files are encrypted for security reasons.
In order to read them you have to provide the pass phrases.
Enter password :
04-Jan-2018 10:40:56.915 SEVERE [main] org.apache.coyote.AbstractProtocol.init Failed to initialize end point associated with ProtocolHandler ["http-apr-8443"]
 java.lang.Exception: Unable to load certificate key /usr/local/tomcat/conf/ssl/t-key.pem (error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt)
        at org.apache.tomcat.jni.SSLContext.setCertificate(Native Method)
        at org.apache.tomcat.util.net.AprEndpoint.bind(AprEndpoint.java:657)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:742)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:458)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:960)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:568)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:851)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:576)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:599)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:310)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:484)

04-Jan-2018 10:40:56.919 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[HTTP/1.1-8443]]
 org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8443]]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
        at org.apache.catalina.core.StandardService.initInternal(StandardService.java:568)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:851)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:576)
        at org.apache.catalina.startup.Catalina.load(Catalina.java:599)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:310)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:484)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:962)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        ... 12 more
Caused by: java.lang.Exception: Unable to load certificate key /usr/local/tomcat/conf/ssl/t-key.pem (error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt)
        at org.apache.tomcat.jni.SSLContext.setCertificate(Native Method)
        at org.apache.tomcat.util.net.AprEndpoint.bind(AprEndpoint.java:657)
        at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:742)
        at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:458)
        at org.apache.catalina.connector.Connector.initInternal(Connector.java:960)
        ... 13 more
````

**Comment by heikofriedrich** [comment]
certitfacte password didnt fit to won-server-cert files, certificates where old while password was changed (certificate files are only regenerated if they do not already exist, if an old version exists they are not regenerated):
````
root@satvm06:/usr/share/webofneeds/uki/won-server-certs# ls -l
total 20
-rw-r--r-- 1 root root 1196 Jan  3 12:55 t-cert.pem
-rw-r--r-- 1 root root 2445 Jan  3 12:55 t-key-cert.pfx
-rw-r--r-- 1 root root 1834 Jan  3 12:55 t-key.pem
-rw-r--r-- 1 root root 2188 Jan  3 12:55 t-keystore.jks
-rw-r--r-- 1 won  won    21 Jan  4 11:39 won_certificate_passwd_file
````
=> password new, certificates outdated 
=> deleted whole folder and redeployed (password file gets generated newly and certificates are also generated newly)
