### ISSUE TITLE
Error while parsing N-quad

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#1579]
Caused by newlines(`\n`) (and possibly other control characters) in RDF literals.
Steps to reproduce:
1. Create a conversation in the owner webapp
2. toggle RDF mode on
3. in the conversation  view, enter the following string into the turtle box:
```
<this:messageuri> won:hasTextMessage "This message will look normal when received in a live conversation by the other side. \nHowever, after a reload, there will be an error logged in the js console and the message will not be rendered in the view - in both sides of the conversation."  .
```
4. Note that the message looks normal, no errors in the console
5. Reload the page
6. Note that the message is not displayed and there is an error in the console.

The console then shows something like this:
```
utils.js:494 failed lookup for https://satvm05.researchstudio.at/won/resource/event/i2a853lefm1ga52khowx in utils.js:urisToLookupMap Error while parsing N-Quads; invalid quad. 

 Error
    at new Fa (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:46:26387)
    at da (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:45:30456)
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:46:9224
    at j.run (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:54:7163)
    at i (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:54:6654) 

 (2) ["https://satvm05.researchstudio.at/won/resource/event/aidkcbaaxeyl2x465vil", "https://satvm05.researchstudio.at/won/resource/event/i2a853lefm1ga52khowx"]0: "https://satvm05.researchstudio.at/won/resource/event/aidkcbaaxeyl2x465vil"1: "https://satvm05.researchstudio.at/won/resource/event/i2a853lefm1ga52khowx"length: 2__proto__: Array(0) 

 (2) ["https://satvm05.researchstudio.at/won/resource/event/aidkcbaaxeyl2x465vil", "https://satvm05.researchstudio.at/won/resource/event/i2a853lefm1ga52khowx"]0: "https://satvm05.researchstudio.at/won/resource/event/aidkcbaaxeyl2x465vil"1: "https://satvm05.researchstudio.at/won/resource/event/i2a853lefm1ga52khowx"length: 2__proto__: Array(0) 

 Fa {stack: "Error↵    at new Fa (https://satvm05.researchstudi…io.at/owner/generated/app_jspm.bundle.js:54:6654)", name: "jsonld.ParseError", message: "Error while parsing N-Quads; invalid quad.", details: {…}}details: {line: 3}message: "Error while parsing N-Quads; invalid quad."name: "jsonld.ParseError"stack: "Error↵    at new Fa (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:46:26387)↵    at da (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:45:30456)↵    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:46:9224↵    at j.run (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:54:7163)↵    at i (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:54:6654)"__proto__: Error
    at h (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:46:26581)
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:47:23211
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:47:23349
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:47:23352
    at j (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:2:7944)
    at i (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:2:7581)
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:2:8022
    at https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:47:23442
    at j (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:2:7944)
    at f (https://satvm05.researchstudio.at/owner/generated/app_jspm.bundle.js:2:6723)
(anonymous) @ utils.js:494
Promise.catch (async)
(anonymous) @ utils.js:492
H @ utils.js:491
(anonymous) @ linkeddata-service-won.js:1686
i @ runtime.js:35
(anonymous) @ runtime.js:195
a.(anonymous function) @ runtime.js:59
i @ runtime.js:35
c @ runtime.js:87
(anonymous) @ runtime.js:95
Promise.then (async)
c @ runtime.js:94
(anonymous) @ runtime.js:113
b @ $.export.js:27
d @ runtime.js:112
d @ runtime.js:116
a.(anonymous function) @ runtime.js:59
B.async @ runtime.js:123
v.getWonMessagesOfConnection @ linkeddata-service-won.js:1685
(anonymous) @ connections-actions.js:323
(anonymous) @ index.js:13
(anonymous) @ router-middleware.js:30
(anonymous) @ bindActionCreators.js:8
(anonymous) @ post-messages.js:372
Promise.then (async)
value @ post-messages.js:365
(anonymous) @ post-messages.js:351
(anonymous) @ angular.js:17929
$digest @ angular.js:18264
$apply @ angular.js:18534
(anonymous) @ angular.js:27349
db @ angular.js:3774
c @ angular.js:3762
```

**Comment by quasarchimaere** [comment]
caused by: 
https://github.com/digitalbazaar/jsonld.js/issues/242

**Comment by fkleedorfer** [comment]
We've fixed our input, all we can do now is hope for jsonld.js to fix their bug
