### ISSUE TITLE
NumericIntervalType - custom separator

### ISSUE THREAD

**Issue by atus** [researchstudio-sat/webofneeds#2]
Adding a custom separator like this

```
<fieldType name="numericIntervalType" class="won.matcher.solr.intervals.NumericIntervalType" subFieldSuffix="_numericInterval" separator="-"/>
```

produces an error

```
14:35:52,915 ERROR main plugin.AbstractPluginLoader:151 - java.lang.RuntimeException: schema fieldtype numericIntervalType(won.matcher.solr.intervals.NumericIntervalType) invalid arguments:{separator=-}
at org.apache.solr.schema.FieldType.setArgs(FieldType.java:168)
at org.apache.solr.schema.IndexSchema$1.init(IndexSchema.java:467)
at org.apache.solr.schema.IndexSchema$1.init(IndexSchema.java:435)
at org.apache.solr.util.plugin.AbstractPluginLoader.load(AbstractPluginLoader.java:175)
at org.apache.solr.schema.IndexSchema.readSchema(IndexSchema.java:480)
at org.apache.solr.schema.IndexSchema.<init>(IndexSchema.java:125)
at org.apache.solr.core.CoreContainer.create(CoreContainer.java:461)
at org.apache.solr.core.CoreContainer.load(CoreContainer.java:316)
at org.apache.solr.core.CoreContainer.load(CoreContainer.java:207)
at org.apache.solr.core.CoreContainer$Initializer.initialize(CoreContainer.java:130)
at won.matcher.query.rdf.TimeIntervalTest.setup(TimeIntervalTest.java:49)
...
```

**Comment by quasarchimaere** [comment]
is done
