### ISSUE TITLE
sparql matcher dies

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2472]
Quite frequently, the sparql matcher dies and does not come back up.

**Comment by fkleedorfer** [comment]
There seems to be a  combination of reasons:
1. it processes a need that is formed unexpectedly - maybe a persona. Trying to read its flags, the NeedModelWrapper throws a NPE:
```
java.lang.NullPointerException
        at won.protocol.util.NeedModelWrapper.hasFlag(NeedModelWrapper.java:287)
        at won.matcher.sparql.actor.SparqlMatcherActor.lambda$processActiveNeedEvent$4(SparqlMatcherActor.java:252)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1548)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at won.matcher.sparql.actor.SparqlMatcherActor.processActiveNeedEvent(SparqlMatcherActor.java:275)
        at won.matcher.sparql.actor.SparqlMatcherActor.onReceive(SparqlMatcherActor.java:130)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
Then the actor dies and its supervisor tries to start it again, but that fails, too:
```
[ERROR] [10/24/2018 16:18:12.800] [ClusterSystem-akka.actor.default-dispatcher-15] [akka://ClusterSystem/user/MatcherPubSubActor] actor name [SparqlMatcherPool] is not unique!
akka.actor.PostRestartException: akka://ClusterSystem/user/MatcherPubSubActor: exception post restart (class java.lang.NullPointerException)
        at akka.actor.dungeon.FaultHandling$$anonfun$6.apply(FaultHandling.scala:250)
        at akka.actor.dungeon.FaultHandling$$anonfun$6.apply(FaultHandling.scala:248)
        at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:303)
        at akka.actor.dungeon.FaultHandling$$anonfun$handleNonFatalOrInterruptedException$1.applyOrElse(FaultHandling.scala:298)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.actor.dungeon.FaultHandling$class.finishRecreate(FaultHandling.scala:248)
        at akka.actor.dungeon.FaultHandling$class.faultRecreate(FaultHandling.scala:76)
        at akka.actor.ActorCell.faultRecreate(ActorCell.scala:374)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:464)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
        at akka.dispatch.Mailbox.run(Mailbox.scala:223)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: akka.actor.InvalidActorNameException: actor name [SparqlMatcherPool] is not unique!
        at akka.actor.dungeon.ChildrenContainer$NormalChildrenContainer.reserve(ChildrenContainer.scala:129)
        at akka.actor.dungeon.Children$class.reserveChild(Children.scala:130)
        at akka.actor.ActorCell.reserveChild(ActorCell.scala:374)
        at akka.actor.dungeon.Children$class.makeChild(Children.scala:268)
        at akka.actor.dungeon.Children$class.actorOf(Children.scala:42)
        at akka.actor.ActorCell.actorOf(ActorCell.scala:374)
        at won.matcher.sparql.actor.MatcherPubSubActor.preStart(MatcherPubSubActor.java:66)
        at akka.actor.Actor$class.postRestart(Actor.scala:566)
        at akka.actor.UntypedActor.postRestart(UntypedActor.scala:163)
        at akka.actor.Actor$class.aroundPostRestart(Actor.scala:504)
        at akka.actor.UntypedActor.aroundPostRestart(UntypedActor.scala:95)
        at akka.actor.dungeon.FaultHandling$class.finishRecreate(FaultHandling.scala:239)

```
