### ISSUE TITLE
Edit and Post this too fails

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2859]
Edit of interests (both Lunch and Cycling) fails because of invalid JSON-LD generated in the owner webapp. The exception on the server is, 
```

1.4.19 15:54:08.378 [https-jsse-nio2-8443-exec-8] ERROR o.s.w.s.h.ExceptionWebSocketHandlerDecorator - Closing session due to exception for WebSocketServerSockJsSession[id=deq3pyyi]
org.apache.jena.riot.RiotException: invalid @id value: value of @id must be a string
        at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:137) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.lang.JsonLDReader.read$(JsonLDReader.java:162) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.lang.JsonLDReader.read(JsonLDReader.java:70) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFParser.read(RDFParser.java:302) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:288) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:237) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:417) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:880) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:614) ~[jena-arq-3.5.0.jar:3.5.0]
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:601) ~[jena-arq-3.5.0.jar:3.5.0]
        at won.protocol.message.WonMessageDecoder.decode(WonMessageDecoder.java:29) ~[won-core-0.4-SNAPSHOT.jar:na]

```

**Comment by quasarchimaere** [comment]
please also check isValid -> saving a need shouldnt be possible if mandatory info is missing

**Comment by quasarchimaere** [comment]
also trying to create a usecase after the same usecase has been edited or used as a post this too template might result in changing the usecase draft itself... not sure if thats the case though (just a reminder for me)
