### ISSUE TITLE
Error editing need content

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2867]
In some cases we get errors like this on the node:
```
3.4.19 08:04:09.877 [ActiveMQ BrokerService[wonBroker] Task-647] ERROR o.a.a.broker.TransportConnector - Could not accept connection from tcp://172.18.0.1:59756: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
3.4.19 08:04:12.379 [Camel (wonNodeCamel) thread #3 - JmsConsumer[OwnerProtocol.in]] INFO  w.p.m.p.c.WonMessageProcessorCamelAdapter - re-throwing exception won.protocol.message.processor.exception.WonMessageProcessingException: java.security.SignatureException: Could not verify message https://node.matchat.org/won/resource/event/w1vvps6l5y9t: No public key found for https://node.matchat.org/won/resource/event/w1vvps6l5y9t#need-sig caught calling adaptee won.protocol.message.processor.impl.SignatureCheckingWonMessageProcessor@3b9c05f with message won.protocol.message.WonMessage@5691a480 (type: REPLACE, direction: FROM_OWNER, recipient:null)
3.4.19 08:04:12.383 [Camel (wonNodeCamel) thread #3 - JmsConsumer[OwnerProtocol.in]] INFO  w.n.c.p.general.FailResponder - Caught error while processing WON message https://node.matchat.org/won/resource/event/w1vvps6l5y9t (type:REPLACE) : WonMessageProcessingException: java.security.SignatureException: Could not verify message https://node.matchat.org/won/resource/event/w1vvps6l5y9t: No public key found for https://node.matchat.org/won/resource/event/w1vvps6l5y9t#need-sig - sending FailureResponse (more info on log level DEBUG)
```

**Comment by quasarchimaere** [comment]
Can't reproduce this error, can someone else have a look at it, need-edit seems fine to me

**Comment by sigpie** [comment]
Error logged on owner when deleting a need. According to @quasarchimaere it might have a similar cause. 

```17.4.19 15:18:26.573 [Camel (wonOwnerCamel) thread #10 - JmsConsumer[OwnerProtocol.Out.9b946823153a026f114eda9538de5179e20bdd78423a5363e2ac203d]] WARN  o.a.c.c.jms.EndpointMessageListener -
				Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - won.protocol.message.processor.exception.WonMessageProcessingException: Could not verify message https://nodeblue.master.matchat.org/won/resource/event/u8ueg28zafmp]
org.apache.camel.RuntimeCamelException: won.protocol.message.processor.exception.WonMessageProcessingException: Could not verify message https://nodeblue.master.matchat.org/won/resource/event/u8ueg28zafmp
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1344) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:186) ~[camel-jms-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.CamelInternalProcessor$InternalCallback.done(CamelInternalProcessor.java:251) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:106) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:114) ~[camel-jms-2.12.1.jar:2.12.1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:744) ~[spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:682) ~[spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:649) ~[spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:317) [spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:255) [spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1168) [spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1160) [spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1057) [spring-jms-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_202]
Caused by: won.protocol.message.processor.exception.WonMessageProcessingException: Could not verify message https://nodeblue.master.matchat.org/won/resource/event/u8ueg28zafmp
	at won.protocol.message.processor.impl.SignatureCheckingWonMessageProcessor.process(SignatureCheckingWonMessageProcessor.java:66) ~[classes/:na]
	at won.protocol.message.processor.camel.WonMessageProcessorCamelAdapter.process(WonMessageProcessorCamelAdapter.java:56) ~[classes/:na]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:97) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:67) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint.onExchange(ProcessorEndpoint.java:103) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:103) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) ~[camel-core-2.12.1.jar:2.12.1]
	... 13 common frames omitted
Caused by: won.protocol.rest.LinkedDataFetchingException: caught a HttpClientErrorException exception, for https://nodeblue.master.matchat.org/won/resource/need/hekmj7pjsa2l. Underlying error message is: 410 , response Body: 
	at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:93) ~[classes/:na]
	at won.protocol.rest.LinkedDataRestClientHttps.readResourceDataWithHeaders(LinkedDataRestClientHttps.java:106) ~[classes/:na]
	at won.protocol.rest.LinkedDataRestClientHttps.readResourceDataWithHeaders(LinkedDataRestClientHttps.java:118) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.fetch(CachingLinkedDataSource.java:414) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchWithEtagValidation(CachingLinkedDataSource.java:368) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchAndCacheIfAppropriate(CachingLinkedDataSource.java:283) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchOnlyOnce(CachingLinkedDataSource.java:269) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchOrUseCached(CachingLinkedDataSource.java:212) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:155) ~[classes/:na]
	at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:510) ~[classes/:na]
	at won.protocol.message.processor.impl.SignatureCheckingWonMessageProcessor.getRequiredPublicKeys(SignatureCheckingWonMessageProcessor.java:108) ~[classes/:na]
	at won.protocol.message.processor.impl.SignatureCheckingWonMessageProcessor.process(SignatureCheckingWonMessageProcessor.java:59) ~[classes/:na]
	... 32 common frames omitted
Caused by: org.springframework.web.client.HttpClientErrorException: 410 
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:86) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:708) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:661) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:636) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:557) ~[spring-web-4.3.18.RELEASE.jar:4.3.18.RELEASE]
	at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:79) ~[classes/:na]
	... 43 common frames omitted```
