### ISSUE TITLE
Posting 'Plan a ride' very unreliable

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#2988]
Steps to reproduce: 
* have Persona
* have cycling interest
* create a ride (->'plan a ride') using the persona.

Trying this, (in ff and chrome), a screen like the following is not unusual:
![grafik](https://user-images.githubusercontent.com/551624/60723107-09ea2880-9f33-11e9-924e-414a43b759b7.png)

It takes quite a long time until the server-side action for accepting the holder connection is sent (I understand this may or may not have to do with the owner webapp). Even after that, the view remains broken and a reload is necessary. 
The expected result (a new ride within the persona's inventory) is not always achieved. Sometimes, no new atoms are created (or at least shown in the GUI)

**Comment by quasarchimaere** [comment]
browser log entries?

**Comment by fkleedorfer** [comment]
Nothing unusual - no warnings , no errors

**Comment by fkleedorfer** [comment]
Oh, and the view shown when I navigate to the ride, in those cases in which one is created, the external view is shown (I believe): 
![grafik](https://user-images.githubusercontent.com/551624/60728596-02ca1700-9f41-11e9-89d7-7d4f1da39566.png)

**Comment by quasarchimaere** [comment]
yes that seems to be the external view, which would indicate that we either dont store the created atom as our own, or (more likely since the white placeholder seeming bug appears) the createSuccesful action is not published due some ws mishap

**Comment by fkleedorfer** [comment]
Affects other use cases, too, e.g. 'Social-> Go out'. Same behaviour (white placeholder). Here's some logs and the screensot:
```
[DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input id=​"loginPassword" placeholder=​"Password" ng-model=​"self.password" type=​"password" required ng-keyup=​"self.formKeyUp($event)​" class=​"ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required ng-touched" style>​
atom-reducer-main.js:500 Can't add the connection( https://node.matchat.org/won/resource/connection/bw3b9assdbkpm87ucjgb ) the atom is not stored in the state yet
p @ atom-reducer-main.js:500
n @ reducers.js:251
(anonymous) @ reducers.js:253
(anonymous) @ immutable.js:1377
Yt.iterate @ immutable.js:1744
Pt.iterate.Ht.iterate @ immutable.js:1737
Pt.iterate.Ht.iterate @ immutable.js:1737
Tt.__iterate @ immutable.js:1375
forEach @ immutable.js:4381
(anonymous) @ reducers.js:245
(anonymous) @ index.js:14
(anonymous) @ index.js:13
h @ createStore.js:165
(anonymous) @ digestMiddleware.js:3
(anonymous) @ piwik.js:130
(anonymous) @ index.js:9
(anonymous) @ router-middleware.js:40
c @ messaging-agent.js:136
(anonymous) @ messaging-agent.js:371
Promise.then (async)
g @ messaging-agent.js:364
t.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
w._transportMessage @ main.js:276
r.emit @ emitter.js:50
ws.onmessage @ websocket.js:35
atom-reducer-main.js:410 Open/Connect success for a connection that is not stored in the state yet, connUri:  https://node.matchat.org/won/resource/connection/bw3b9assdbkpm87ucjgb
p @ atom-reducer-main.js:410
n @ reducers.js:251
(anonymous) @ reducers.js:253
(anonymous) @ immutable.js:1377
Yt.iterate @ immutable.js:1744
Pt.iterate.Ht.iterate @ immutable.js:1737
Pt.iterate.Ht.iterate @ immutable.js:1737
Tt.__iterate @ immutable.js:1375
forEach @ immutable.js:4381
(anonymous) @ reducers.js:245
(anonymous) @ index.js:14
(anonymous) @ index.js:13
h @ createStore.js:165
(anonymous) @ digestMiddleware.js:3
(anonymous) @ piwik.js:130
(anonymous) @ index.js:9
(anonymous) @ router-middleware.js:40
c @ messaging-agent.js:130
(anonymous) @ messaging-agent.js:371
Promise.then (async)
g @ messaging-agent.js:364
t.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
w._transportMessage @ main.js:276
r.emit @ emitter.js:50
ws.onmessage @ websocket.js:35
linkeddata-service-won.js:775 GET https://www.matchat.org/owner/rest/linked-data/?requester=https:%2F%2Fnode.matchat.org%2Fwon%2Fresource%2Fatom%2Fms3ndmmk14zi&uri=https:%2F%2Fnode.matchat.org%2Fwon%2Fresource%2Fconnection%2Ftheytgr4baffcw6460mr%2Fevents 502
J @ linkeddata-service-won.js:775
(anonymous) @ linkeddata-service-won.js:567
tryCatch @ runtime.js:45
invoke @ runtime.js:271
prototype.<computed> @ runtime.js:97
m @ linkeddata-service-won.js:1957
i @ linkeddata-service-won.js:1957
Promise.then (async)
m @ linkeddata-service-won.js:1957
i @ linkeddata-service-won.js:1957
(anonymous) @ linkeddata-service-won.js:1957
(anonymous) @ linkeddata-service-won.js:1957
(anonymous) @ linkeddata-service-won.js:528
i.default.getNode @ linkeddata-service-won.js:1369
(anonymous) @ linkeddata-service-won.js:1272
Promise.then (async)
i.default.getConnectionWithEventUris @ linkeddata-service-won.js:1269
g @ state-store.js:68
(anonymous) @ messages-actions.js:226
(anonymous) @ index.js:9
(anonymous) @ router-middleware.js:40
c @ messaging-agent.js:73
(anonymous) @ messaging-agent.js:371
Promise.then (async)
g @ messaging-agent.js:364
t.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:278
w._transportMessage @ main.js:276
r.emit @ emitter.js:50
ws.onmessage @ websocket.js:35
messages-actions.js:270 Change ReceiverConnectionState  true
messages-actions.js:282 Change SenderConnectionState  true
sw.js:4 push event
messages-actions.js:270 Change ReceiverConnectionState  true
messages-actions.js:282 Change SenderConnectionState  true
```
![grafik](https://user-images.githubusercontent.com/551624/60733238-948b5180-9f4c-11e9-89eb-3f5b813bf2be.png)

**Comment by fkleedorfer** [comment]
Can only reproduce this on live.

The cause seems to be a duplicate insert into the wonuser_useratom table (see logs below).

This leads to an exception and the association between the new atom and the user is not made; therefore, the atom is subsequently shown as the atom of someone else. 

Also, due to the exception, which happens when processing the SuccessResponse to the CreateMessage, the SuccessResponse is not forwarded to the webapp, which is why it hangs indefinitely during creation.

owner-webapp server logs:
```
10.7.19 08:07:18.842 [Camel (wonOwnerCamel) thread #8 - JmsConsumer[OwnerProtocol.Out.35a592a1538bfd931dfbdccb75c856da3b8bc610d2c67833427fcad2]] INFO  w.o.w.
10.7.19 08:07:19.060 [Camel (wonOwnerCamel) thread #8 - JmsConsumer[OwnerProtocol.Out.35a592a1538bfd931dfbdccb75c856da3b8bc610d2c67833427fcad2]] WARN  w.o.w.
org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [uk_e6i3wwqxp9hxtrnl7yvnehqoj]; nested exception
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:278) ~[spring-orm-4.3.18.RELEASE.j
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:244) ~[spring-orm-4.3.18.RELEASE.jar:
        at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521) ~[spring-orm-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:765) ~[spring-tx-
        at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:734) ~[spring-tx-4.3.18.
        at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:518) ~[spring-t
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:292) ~[spring-tx-4.3.18
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.18.RELEASE.jar:4.3.18.RE
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.R
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136) ~[spring-tx
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.R
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMet
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.R
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.R
        at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterc
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.R
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.18.RELEASE.jar:4.3.18.RELEASE]
        at com.sun.proxy.$Proxy77.save(Unknown Source) ~[na:na]
        at won.owner.web.websocket.WonWebSocketHandler.saveAtomUriWithUser(WonWebSocketHandler.java:676) [classes/:na]
        at won.owner.web.websocket.WonWebSocketHandler.sendMessageForSession(WonWebSocketHandler.java:596) [classes/:na]
        at won.owner.web.websocket.WonWebSocketHandler.process(WonWebSocketHandler.java:304) [classes/:na]
        at won.owner.service.impl.OwnerApplicationService.process(OwnerApplicationService.java:48) [won-owner-0.4-SNAPSHOT.jar:na]
        at won.protocol.message.processor.camel.WonMessageProcessorCamelAdapter.process(WonMessageProcessorCamelAdapter.java:56) [won-core-0.4-SNAPSHOT.jar:n
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:97) [camel-core-2.12.1.jar:2.12.1]
[...]
```

**Comment by fkleedorfer** [comment]
The violated constratint turns out to be
`CREATE UNIQUE INDEX uk_e6i3wwqxp9hxtrnl7yvnehqoj ON wonuser_userneed (userneeds_id);`

**Comment by fkleedorfer** [comment]
#2994 did not resolve this. 
It seems that in this situation, we try to add an older atom again instead of adding the newly created one.
