### ISSUE TITLE
Need creation is not working in old UI

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#403]
Need creation is not working anymore on master and devel branch with old UI.
old UI doesnt forward to need created page after clicking "Create Need" anymore

Suspected reason: There are too many needs in the db 
=> out of mem error on dev owner 
=> on master (no exceptions), but I deleted needs in postgres db => retest with fresh db => UI working again
=> no exception in wonnode logs

Issues should be retested in new UI, if UI can handle a lot of needs in db

**Comment by fkleedorfer** [comment]
@yanapanchenko I think that is what you described: owner apps tend to run out of memory (for no apparent reason on our devel/master sytems).. right?

**Comment by fkleedorfer** [comment]
maybe related: I think we need some kind of limit on number of hints sent. 
Extending that thought: maybe it would be good to have a mechanism by which the user can signal that they wish for more hints, and as a result, matchers would send the next batch. as we already have the backchannel to the matcher, that would not be too hard.

**Comment by heikofriedrich** [comment]
not sure if this exception is related to the problem but it seems to occur in conjunction with the oversed need creation behavior: 

INFO [SockJsScheduler-2] org.apache.coyote.AbstractProcessor.setErrorState An error occurred in processing while on a non-container thread. The connection will be closed immediately
 java.io.IOException: APR error: -70014
        at org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:291)
        at org.apache.coyote.http11.InternalAprOutputBuffer.writeToSocket(InternalAprOutputBuffer.java:244)
        at org.apache.coyote.http11.InternalAprOutputBuffer.flushBuffer(InternalAprOutputBuffer.java:213)
        at org.apache.coyote.http11.AbstractOutputBuffer.flush(AbstractOutputBuffer.java:305)
        at org.apache.coyote.http11.AbstractHttp11Processor.action(AbstractHttp11Processor.java:765)
        at org.apache.coyote.Response.action(Response.java:177)
        at org.apache.catalina.connector.OutputBuffer.doFlush(OutputBuffer.java:349)
        at org.apache.catalina.connector.OutputBuffer.flush(OutputBuffer.java:317)
        at org.apache.catalina.connector.Response.flushBuffer(Response.java:511)
        at org.apache.catalina.connector.ResponseFacade.flushBuffer(ResponseFacade.java:318)
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
        at org.springframework.session.web.http.OnCommittedResponseWrapper.flushBuffer(OnCommittedResponseWrapper.java:143)
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
        at javax.servlet.ServletResponseWrapper.flushBuffer(ServletResponseWrapper.java:176)
        at org.springframework.security.web.context.SaveContextOnUpdateOrErrorResponseWrapper.flushBuffer(SaveContextOnUpdateOrErrorResponseWrapper.java:119)
        at org.springframework.http.server.ServletServerHttpResponse.flush(ServletServerHttpResponse.java:90)
        at org.springframework.web.socket.sockjs.transport.session.AbstractHttpSockJsSession.writeFrameInternal(AbstractHttpSockJsSession.java:343)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.writeFrame(AbstractSockJsSession.java:336)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.sendHeartbeat(AbstractSockJsSession.java:383)
        at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession$2.run(AbstractSockJsSession.java:401)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by heikofriedrich** [comment]
its also not working in the new gui

**Comment by heikofriedrich** [comment]
things we just found out:
- if you use a local developer version of the owner application it works (with the remote wonnode), this uses a local in-memory postgres database by default (hsql)
- however we changed the postgresql db connection of the local owner to use the postgres deployed on the server (satsrv04) and then the need cannot be published anymore
=> so the problem is related to the database used

**Comment by heikofriedrich** [comment]
created a copy of the current postgres db with needs that is still working for retest when we have a version of postgres container that will break the application again => name: postgres_db_with_needs_still_running

install@satsrv04:~$ docker -H localhost:2375 images
REPOSITORY                             TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
postgres_db_with_needs_still_running   latest              524a3dbbdb53        2 minutes ago       265.9 MB

**Comment by heikofriedrich** [comment]
just found some errors in postgres pg_log (/var/lib/postgresql/data/pg_log):

STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
STATEMENT:  select ownerappli0_.id as id1_8_, ownerappli0_.incomingEndpoint as incoming2_8_, ownerappli0_.ownerApplicationId as ownerApp3_8_ from ownerApplication ownerappli0_ where ownerappli0_.ownerApplicationId=$1
ERROR:  relation "ownerapplication" does not exist at character 135
...

**Comment by heikofriedrich** [comment]
The problem was that the registration of messaging routes of the owner to the wonnode was not done correctly if if was already saved in the database, so for the first time the owner starts with a fresh database everythings working fine, but after the server restarts the owner does the incomplete registration and remoteBrokerEndpoint for camel message sending was null, so the owner didnt send the message to the right wonnode and the wonnode never received the message and the gui was stuck. fixed with commit c43ef417816a38b4f153ce723e4218433efd7a16
