### ISSUE TITLE
Owner and Wonnode throw exception when not able to access public matcher uri

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#450]
wonnode and owner throw exception atfer receiving hints from matcher cause they cannot access the public matcher uri "matcher.siren.uri.solr.server.public=http://satcluster01.researchstudio.at:8984/solr/#/won/" => there should be no exception in this case but a warning

=> maybe this even causes that matches are not properly displayed in the gui??

23.3.16 15:04:16.354 [Camel (wonOwnerCamel) thread #38 - JmsConsumer[OwnerProtocol.Out.84fb83a11aa4504aaff50f2e89829869ef2415df]] INFO  w.p.u.l.CachingLinkedDataSource - Couldn't fetch resource http://satcluster01.researchstudio.at:8984/solr/#/won/
net.sf.ehcache.CacheException: Could not fetch object for cache entry with key "http://satcluster01.researchstudio.at:8984/solr/#/won/".
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.get(SelfPopulatingCache.java:79) ~[ehcache-core-2.6.8.jar:na]
        at net.sf.ehcache.constructs.blocking.BlockingCache.get(BlockingCache.java:308) ~[ehcache-core-2.6.8.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:80) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.service.impl.WonNodeInformationServiceImpl.getWonNodeInformation(WonNodeInformationServiceImpl.java:34) [won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.message.processor.impl.UriConsistencyCheckingWonMessageProcessor.process(UriConsistencyCheckingWonMessageProcessor.java:45) [won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.message.processor.camel.WonMessageProcessorCamelAdapter.process(WonMessageProcessorCamelAdapter.java:51) [won-core-0.2-SNAPSHOT.jar:na]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:97) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:67) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.impl.ProcessorEndpoint.onExchange(ProcessorEndpoint.java:103) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103) [camel-jms-2.12.1.jar:2.12.1]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:685) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:623) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:591) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:308) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: java.lang.IllegalArgumentException: caught a clientHandler exception, which may indicate that the URI that was accessed isn't a linked data URI, please check http://satcluster01.researchstudio.at:8984/solr/#/won/. Underlying error message is: Could not extract response: no suitable HttpMessageConverter found for response type [interface com.hp.hpl.jena.query.Dataset] and content type [text/html;charset=UTF-8]
        at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:81) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.rest.LinkedDataRestClientHttps.readResourceData(LinkedDataRestClientHttps.java:123) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource$LinkedDataCacheEntryFactory.createEntry(CachingLinkedDataSource.java:149) ~[won-core-0.2-SNAPSHOT.jar:na]
        at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.get(SelfPopulatingCache.java:73) ~[ehcache-core-2.6.8.jar:na]
        ... 32 common frames omitted
Caused by: org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [interface com.hp.hpl.jena.query.Dataset] and content type [text/html;charset=UTF-8]
        at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:108) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:812) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:796) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:576) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:465) ~[spring-web-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:69) ~[won-core-0.2-SNAPSHOT.jar:na]
        ... 35 common frames omitted

**Comment by heikofriedrich** [comment]
exception was only a info message shouldnt have affacted anything, changed it to a warning => fixed with 47bac4ce90173635c718343799b392d2cc13965c
