### ISSUE TITLE
Need to delete the database after new certificates created

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#453]
Currently some connection information is saved in the database that is related to the certificate. if a new certificate is created, the owner application throws exceptions when trying to create a new need. Therefore currently the database has to be emptied every time a new certificate is created. 

Exception thrown:
javax.jms.JMSException: Could not connect to broker URL: ssl://satsrv05.researchstudio.at:61616. Reason: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:35) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:293) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:238) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:184) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:351) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:295) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:227) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:413) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.refreshSharedConnection(AbstractJmsListeningContainer.java:398) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.refreshConnectionUntilSuccessful(DefaultMessageListenerContainer.java:907) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.recoverAfterListenerSetupFailure(DefaultMessageListenerContainer.java:882) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815) ~[na:1.8.0_66-internal]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpBufferedOutputStream.flush(TcpBufferedOutputStream.java:115) ~[activemq-client-5.8.0.jar:5.8.0]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpTransport.oneway(TcpTransport.java:176) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.doOnewaySend(AbstractInactivityMonitor.java:322) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.oneway(AbstractInactivityMonitor.java:304) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:168) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:84) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:74) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:273) ~[activemq-client-5.8.0.jar:5.8.0]
        ... 12 common frames omitted
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:90) ~[na:1.8.0_66-internal]
        at sun.security.validator.Validator.getInstance(Validator.java:179) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105) ~[na:1.8.0_66-internal]
        at won.cryptography.ssl.TrustManagerWrapperWithTrustService.checkServerTrusted(TrustManagerWrapperWithTrustService.java:55) ~[won-core-0.2-SNAPSHOT.jar:na]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:922) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[na:1.8.0_66-internal]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_66-internal]
        ... 23 common frames omitted
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200) ~[na:1.8.0_66-internal]
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120) ~[na:1.8.0_66-internal]
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104) ~[na:1.8.0_66-internal]
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:88) ~[na:1.8.0_66-internal]
        ... 38 common frames omitted

**Comment by heikofriedrich** [comment]
realted issue  #454

**Comment by fkleedorfer** [comment]
Cleaning up old issues. This issue points to a more general admin feature in the owner webapp (and even one for the node), which are out of scope right now.
