### ISSUE TITLE
Faulty Owner Configuration

### ISSUE THREAD

**Issue by quasarchimaere** [researchstudio-sat/webofneeds#628]
`11:08:41.094 [http-apr-8443-exec-5] DEBUG w.p.u.linkeddata.WonLinkedDataUtils - base resource https://satsrv06.researchstudio.at:443/won/resource has no won:hasWonNode property
11:08:41.094 [http-apr-8443-exec-5] DEBUG won.protocol.jms.ActiveMQServiceImpl - wonNodeUri: null
11:08:41.094 [http-apr-8443-exec-5] WARN w.p.u.l.CachingLinkedDataSource - Couldn't fetch resource null
11:08:41.095 [http-apr-8443-exec-5] DEBUG w.p.u.l.CachingLinkedDataSource - Exception is:
net.sf.ehcache.CacheException: Could not fetch object for cache entry with key "null".
 at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.get(SelfPopulatingCache.java:79) ~[ehcache-core-2.6.8.jar:na]
 at net.sf.ehcache.constructs.blocking.BlockingCache.get(BlockingCache.java:308) ~[ehcache-core-2.6.8.jar:na]
 at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:80) ~[won-core-0.2-SNAPSHOT.jar:na]
 at won.protocol.jms.ActiveMQServiceImpl.getBrokerEndpoint(ActiveMQServiceImpl.java:133) [won-core-0.2-SNAPSHOT.jar:na]
 at won.owner.messaging.OwnerProtocolCommunicationServiceImpl.configureCamelEndpoint(OwnerProtocolCommunicationServiceImpl.java:153) [won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.messaging.OwnerProtocolCommunicationServiceImpl.register(OwnerProtocolCommunicationServiceImpl.java:97) [won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.messaging.OwnerWonMessageSenderJMSBased.getOwnerApplicationIdAndRegisterIfNecessary(OwnerWonMessageSenderJMSBased.java:115) [won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:96) [won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.service.impl.OwnerApplicationService.sendWonMessage(OwnerApplicationService.java:36) [won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.web.websocket.WonWebSocketHandler.handleTextMessage(WonWebSocketHandler.java:176) [WonWebSocketHandler.class:na]
 at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:55) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:71) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:218) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:194) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.sockjs.transport.handler.SockJsWebSocketHandler.handleTextMessage(SockJsWebSocketHandler.java:92) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.handleTextMessage(StandardWebSocketHandlerAdapter.java:112) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter.access$000(StandardWebSocketHandlerAdapter.java:42) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:82) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.adapter.standard.StandardWebSocketHandlerAdapter$3.onMessage(StandardWebSocketHandlerAdapter.java:79) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.apache.tomcat.websocket.WsFrameBase.sendMessageText(WsFrameBase.java:393) [tomcat-websocket.jar:8.0.24]
 at org.apache.tomcat.websocket.WsFrameBase.processDataText(WsFrameBase.java:494) [tomcat-websocket.jar:8.0.24]
 at org.apache.tomcat.websocket.WsFrameBase.processData(WsFrameBase.java:289) [tomcat-websocket.jar:8.0.24]
 at org.apache.tomcat.websocket.WsFrameBase.processInputBuffer(WsFrameBase.java:130) [tomcat-websocket.jar:8.0.24]
 at org.apache.tomcat.websocket.server.WsFrameServer.onDataAvailable(WsFrameServer.java:60) [tomcat-websocket.jar:8.0.24]
 at org.apache.tomcat.websocket.server.WsHttpUpgradeHandler$WsReadListener.onDataAvailable(WsHttpUpgradeHandler.java:203) [tomcat-websocket.jar:8.0.24]
 at org.apache.coyote.http11.upgrade.AbstractServletInputStream.onDataAvailable(AbstractServletInputStream.java:198) [tomcat-coyote.jar:8.0.24]
 at org.apache.coyote.http11.upgrade.AbstractProcessor.upgradeDispatch(AbstractProcessor.java:96) [tomcat-coyote.jar:8.0.24]
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:663) [tomcat-coyote.jar:8.0.24]
 at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2503) [tomcat-coyote.jar:8.0.24]
 at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:2492) [tomcat-coyote.jar:8.0.24]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.24]
 at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: this cache only resolves URIs and URIs with requester WebIDs to Models
 at won.protocol.util.linkeddata.CachingLinkedDataSource$LinkedDataCacheEntryFactory.createEntry(CachingLinkedDataSource.java:173) ~[won-core-0.2-SNAPSHOT.jar:na]
 at net.sf.ehcache.constructs.blocking.SelfPopulatingCache.get(SelfPopulatingCache.java:73) ~[ehcache-core-2.6.8.jar:na]
 ... 36 common frames omitted
11:08:41.121 [http-apr-8443-exec-5] DEBUG com.hp.hpl.jena.shared.LockMRSW - Lock : http-apr-8443-exec-5
11:08:41.121 [http-apr-8443-exec-5] INFO w.o.s.impl.OwnerApplicationService - could not send WonMessage
java.lang.RuntimeException: could not send message
 at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:110) ~[won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.service.impl.OwnerApplicationService.sendWonMessage(OwnerApplicationService.java:36) ~[won-owner-0.2-SNAPSHOT.jar:na]
 at won.owner.web.websocket.WonWebSocketHandler.handleTextMessage(WonWebSocketHandler.java:176) [WonWebSocketHandler.class:na]
 at org.springframework.web.socket.handler.AbstractWebSocketHandler.handleMessage(AbstractWebSocketHandler.java:43) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.WebSocketHandlerDecorator.handleMessage(WebSocketHandlerDecorator.java:75) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.LoggingWebSocketHandlerDecorator.handleMessage(LoggingWebSocketHandlerDecorator.java:55) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.handler.ExceptionWebSocketHandlerDecorator.handleMessage(ExceptionWebSocketHandlerDecorator.java:71) [spring-websocket-4.1.1.RELEASE.jar:na]
 at org.springframework.web.socket.sockjs.transport.session.AbstractSockJsSession.delegateMessages(AbstractSockJsSession.java:218) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socket.sockjs.transport.session.WebSocketServerSockJsSession.handleMessage(WebSocketServerSockJsSession.java:194) [spring-websocket-4.1.1.RELEASE.jar:4.1.1.RELEASE]
 at org.springframework.web.socke...
`

if you discover that you have this or a similar stacktrace you need to remove the port of your owner.properties configuration (because it is already determined by the protocol)

Changes to make:

`uri.prefix.node.default=${node.default.scheme}://${node.default.host}:${node.default.http.port}/won`
needs to be changed into:
`uri.prefix.node.default=${node.default.scheme}://${node.default.host}/won`

**Comment by fkleedorfer** [comment]
is this still an issue? shouldn't this be part of the documentation?

**Comment by quasarchimaere** [comment]
not an issue
