### ISSUE TITLE
No matches on won node created when behind proxy

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#637]
Hint messages are created by the matcher but not added at the wonnode to the need if the wonnode is behind a proxy e.g. test with proxy (?) satsrv06 (int) or satsrv07 (master)

only matches from debug bot arrive at wonnode, why??

**Comment by heikofriedrich** [comment]
on www.matchat.org matches work however

**Comment by heikofriedrich** [comment]
Message cannot be sent from matcher (satsrv06) to wonnode(satsrv05) behind proxy (satsrv07) => no response within 20 seconds ??

[WARN] [06/23/2016 08:47:57.264] [ClusterSystem-akka.actor.default-dispatcher-6] [akka://ClusterSystem/user/WonNodeControllerActor] Actor encountered error: akka.camel.AkkaCamelException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-fa8c8c72188b-42454-1466670992720-0-28 not received. Exchange[Message: <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u> {
    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u>
            a       <http://purl.org/webofneeds/message#EnvelopeGraph> ;
            <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo> .

    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo>
            a       <http://purl.org/webofneeds/message#FromExternal> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#content-o6g1> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#HintMessage> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv07.researchs... [Body clipped after 1000 chars, total length is 2198]]
23.6.16 08:47:57.265 [ClusterSystem-akka.actor.default-dispatcher-17] INFO  o.a.c.impl.DefaultShutdownStrategy - Starting to graceful shutdown 1 routes (timeout 300 seconds)
[ERROR] [06/23/2016 08:47:57.264] [ClusterSystem-akka.actor.default-dispatcher-17] [akka://ClusterSystem/user/WonNodeControllerActor] The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-fa8c8c72188b-42454-1466670992720-0-28 not received. Exchange[Message: <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u> {
    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u>
            a       <http://purl.org/webofneeds/message#EnvelopeGraph> ;
            <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo> .

    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo>
            a       <http://purl.org/webofneeds/message#FromExternal> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#content-o6g1> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#HintMessage> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv07.researchs... [Body clipped after 1000 chars, total length is 2198]]
akka.camel.AkkaCamelException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-fa8c8c72188b-42454-1466670992720-0-28 not received. Exchange[Message: <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u> {
    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u>
            a       <http://purl.org/webofneeds/message#EnvelopeGraph> ;
            <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo> .

    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo>
            a       <http://purl.org/webofneeds/message#FromExternal> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#content-o6g1> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#HintMessage> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv07.researchs... [Body clipped after 1000 chars, total length is 2198]]
        at akka.camel.ProducerSupport$$anonfun$produce$1.applyOrElse(Producer.scala:73)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
        at akka.camel.javaapi.UntypedProducerActor.onReceive(UntypedProducerActor.scala:49)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:167)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:480)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:97)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:525)
        at akka.actor.ActorCell.invoke(ActorCell.scala:494)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.camel.ExchangeTimedOutException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-fa8c8c72188b-42454-1466670992720-0-28 not received. Exchange[Message: <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u> {
    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#envelope-er2u>
            a       <http://purl.org/webofneeds/message#EnvelopeGraph> ;
            <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo> .

    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo>
            a       <http://purl.org/webofneeds/message#FromExternal> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv07.researchstudio.at/won/resource/event/yvc2a9k0k479rrmcdydo#content-o6g1> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#HintMessage> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv07.researchs... [Body clipped after 1000 chars, total length is 2198]]
        at org.apache.camel.component.jms.reply.ReplyManagerSupport.processReply(ReplyManagerSupport.java:133)
        at org.apache.camel.component.jms.reply.TemporaryQueueReplyHandler.onTimeout(TemporaryQueueReplyHandler.java:61)
        at org.apache.camel.component.jms.reply.CorrelationTimeoutMap.onEviction(CorrelationTimeoutMap.java:53)
        at org.apache.camel.component.jms.reply.CorrelationTimeoutMap.onEviction(CorrelationTimeoutMap.java:30)
        at org.apache.camel.support.DefaultTimeoutMap.purge(DefaultTimeoutMap.java:209)
        at org.apache.camel.support.DefaultTimeoutMap.run(DefaultTimeoutMap.java:159)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

[INFO] [06/23/2016 08:47:57.266] [ClusterSystem-akka.actor.default-dispatcher-18] [akka://ClusterSystem/user/WonNodeControllerActor/ActiveMqHintProducerProtocolActor-f1400e9c-c8fa-4686-8d12-e9c3b65a9edd/$a] Message [akka.camel.FailureResult] from Actor[akka://ClusterSystem/user/WonNodeControllerActor#-1179587443] to Actor[akka://ClusterSystem/user/WonNodeControllerActor/ActiveMqHintProducerProtocolActor-f1400e9c-c8fa-4686-8d12-e9c3b65a9edd/$a#86988128] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[ERROR] [06/23/2016 08:47:57.266] [ClusterSystem-akka.actor.default-dispatcher-18] [akka://ClusterSystem/user/DeadLetterActor] Received dead letter message DeadLetter(FailureResult(org.apache.camel.ExchangeTimedOutException: The OUT message was not received within: 20000 millis due reply message with correlationID: Camel-ID-fa8c8c72188b-42454-1466670992720-0-29 not received. Exchange[Message: <https://satsrv07.researchstudio.at/won/resource/event/rpwgh5570dejdwuyvhdn#envelope-iuje> {
    <https://satsrv07.researchstudio.at/won/resource/event/rpwgh5570dejdwuyvhdn>
            a       <http://purl.org/webofneeds/message#FromExternal> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv07.researchstudio.at/won/resource/event/rpwgh5570dejdwuyvhdn#content-amwr> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#HintMessage> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv07.researchstudio.at/won/resource/need/6558567111349901000> ;
            <http://purl.org/webofneeds/message#hasReceiverNode>
                    <https://satsrv07.researchstudio.at/won/resource> ;
            <http://purl.org/webofneeds/message#hasSenderNode>
                    <http://satsrv06.researchstudio.at:8983/solr/#/won/> ;
          ... [Body clipped after 1000 chars, total length is 2198]],Map()),Actor[akka://ClusterSystem/user/WonNodeControllerActor#-1179587443],Actor[akka://ClusterSystem/user/WonNodeControllerActor/ActiveMqHintProducerProtocolActor-f1400e9c-c8fa-4686-8d12-e9c3b65a9edd/$a#86988128])

**Comment by heikofriedrich** [comment]
with the current build this is not an issue anymore and is working again, even though its unclear why this behavior occured or why it disappeared ??

**Comment by heikofriedrich** [comment]
may it was related to the restarting of the servers since there was a electricity breakdown on friday and the servers had to be restarted? 
other possible explanation, that commit 6f0c0c5ea7e0624820f8807a6f77505e0b85238c fixed the problem, but i dont see why?
