### ISSUE TITLE
Reloading with a lot of needs causes exception on owner

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#677]
on the client:

```
linkeddata-service-won.js: fetching:        https://satsrv04.researchstudio.at:8889/won/resource/need/5062576269167841000
linkeddata-service-won.js:763 linkeddata-service-won.js: fetching:        https://satsrv04.researchstudio.at:8889/won/resource/need/8630413039704447000
linkeddata-service-won.js:763 linkeddata-service-won.js: fetching:        https://satsrv04.researchstudio.at:8889/won/resource/need/3686072706669236000
linkeddata-service-won.js:763 linkeddata-service-won.js: fetching:        https://satsrv04.researchstudio.at:8889/won/resource/need/3645095385494221000
linkeddata-service-won.js:763 linkeddata-service-won.js: fetching:        https://satsrv04.researchstudio.at:8889/won/resource/need/1532447512392972300
linkeddata-service-won.js:770 GET https://192.168.124.53:8443/owner/rest/linked-data/?uri=https:%2F%2Fsatsrv0…srv04.researchstudio.at:8889%2Fwon%2Fresource%2Fneed%2F1532447512392972300 500 (Internal Server Error)(anonymous function) @ linkeddata-service-won.js:770F @ $.export.js:27loadFromOwnServerIntoCache @ linkeddata-service-won.js:762(anonymous function) @ linkeddata-service-won.js:695_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110setTimeout (async)requestTick @ q.js:196nextTick @ q.js:156Promise.then @ q.js:809won.fetch @ linkeddata-service-won.js:694won.ensureLoaded @ linkeddata-service-won.js:652(anonymous function) @ won-message-utils.js:425fetchAllAccessibleAndRelevantData @ won-message-utils.js:425fetchDataForOwnedNeeds @ won-message-utils.js:384(anonymous function) @ won-message-utils.js:378Promise (async)(anonymous function) @ won-message-utils.js:412Promise (async)fetchOwnedNeedUris @ won-message-utils.js:402fetchOwnedData @ won-message-utils.js:376loadingWhileSignedIn @ load-action.js:43(anonymous function) @ load-action.js:33Promise (async)(anonymous function) @ load-action.js:31
linkeddata-service-won.js:770 GET https://192.168.124.53:8443/owner/rest/linked-data/?uri=https:%2F%2Fsatsrv0…srv04.researchstudio.at:8889%2Fwon%2Fresource%2Fneed%2F8630413039704447000 500 (Internal Server Error)(anonymous function) @ linkeddata-service-won.js:770F @ $.export.js:27loadFromOwnServerIntoCache @ linkeddata-service-won.js:762(anonymous function) @ linkeddata-service-won.js:695_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110setTimeout (async)requestTick @ q.js:196nextTick @ q.js:156Promise.then @ q.js:809won.fetch @ linkeddata-service-won.js:694won.ensureLoaded @ linkeddata-service-won.js:652(anonymous function) @ won-message-utils.js:425fetchAllAccessibleAndRelevantData @ won-message-utils.js:425fetchDataForOwnedNeeds @ won-message-utils.js:384(anonymous function) @ won-message-utils.js:378Promise (async)(anonymous function) @ won-message-utils.js:412Promise (async)fetchOwnedNeedUris @ won-message-utils.js:402fetchOwnedData @ won-message-utils.js:376loadingWhileSignedIn @ load-action.js:43(anonymous function) @ load-action.js:33Promise (async)(anonymous function) @ load-action.js:31
linkeddata-service-won.js:770 GET https://192.168.124.53:8443/owner/rest/linked-data/?uri=https:%2F%2Fsatsrv0…srv04.researchstudio.at:8889%2Fwon%2Fresource%2Fneed%2F3686072706669236000 500 (Internal Server Error)(anonymous function) @ linkeddata-service-won.js:770F @ $.export.js:27loadFromOwnServerIntoCache @ linkeddata-service-won.js:762(anonymous function) @ linkeddata-service-won.js:695_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110setTimeout (async)requestTick @ q.js:196nextTick @ q.js:156Promise.then @ q.js:809won.fetch @ linkeddata-service-won.js:694won.ensureLoaded @ linkeddata-service-won.js:652(anonymous function) @ won-message-utils.js:425fetchAllAccessibleAndRelevantData @ won-message-utils.js:425fetchDataForOwnedNeeds @ won-message-utils.js:384(anonymous function) @ won-message-utils.js:378Promise (async)(anonymous function) @ won-message-utils.js:412Promise (async)fetchOwnedNeedUris @ won-message-utils.js:402fetchOwnedData @ won-message-utils.js:376loadingWhileSignedIn @ load-action.js:43(anonymous function) @ load-action.js:33Promise (async)(anonymous function) @ load-action.js:31
linkeddata-service-won.js:770 GET https://192.168.124.53:8443/owner/rest/linked-data/?uri=https:%2F%2Fsatsrv0…srv04.researchstudio.at:8889%2Fwon%2Fresource%2Fneed%2F3645095385494221000 500 (Internal Server Error)(anonymous function) @ linkeddata-service-won.js:770F @ $.export.js:27loadFromOwnServerIntoCache @ linkeddata-service-won.js:762(anonymous function) @ linkeddata-service-won.js:695_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110setTimeout (async)requestTick @ q.js:196nextTick @ q.js:156Promise.then @ q.js:809won.fetch @ linkeddata-service-won.js:694won.ensureLoaded @ linkeddata-service-won.js:652(anonymous function) @ won-message-utils.js:425fetchAllAccessibleAndRelevantData @ won-message-utils.js:425fetchDataForOwnedNeeds @ won-message-utils.js:384(anonymous function) @ won-message-utils.js:378Promise (async)(anonymous function) @ won-message-utils.js:412Promise (async)fetchOwnedNeedUris @ won-message-utils.js:402fetchOwnedData @ won-message-utils.js:376loadingWhileSignedIn @ load-action.js:43(anonymous function) @ load-action.js:33Promise (async)(anonymous function) @ load-action.js:31
linkeddata-service-won.js:770 GET https://192.168.124.53:8443/owner/rest/linked-data/?uri=https:%2F%2Fsatsrv0…srv04.researchstudio.at:8889%2Fwon%2Fresource%2Fneed%2F5062576269167841000 500 (Internal Server Error)(anonymous function) @ linkeddata-service-won.js:770F @ $.export.js:27loadFromOwnServerIntoCache @ linkeddata-service-won.js:762(anonymous function) @ linkeddata-service-won.js:695_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110setTimeout (async)requestTick @ q.js:196nextTick @ q.js:156Promise.then @ q.js:809won.fetch @ linkeddata-service-won.js:694won.ensureLoaded @ linkeddata-service-won.js:652(anonymous function) @ won-message-utils.js:425fetchAllAccessibleAndRelevantData @ won-message-utils.js:425fetchDataForOwnedNeeds @ won-message-utils.js:384(anonymous function) @ won-message-utils.js:378Promise (async)(anonymous function) @ won-message-utils.js:412Promise (async)fetchOwnedNeedUris @ won-message-utils.js:402fetchOwnedData @ won-message-utils.js:376loadingWhileSignedIn @ load-action.js:43(anonymous function) @ load-action.js:33Promise (async)(anonymous function) @ load-action.js:31
utils.js:473 Object {msg: "failed lookup for https://satsrv04.researchstudio.…d/5062576269167841000 in utils.js:urisToLookupMap", error: Object, urisAsArray: Array[5], uris: Array[5]}(anonymous function) @ utils.js:473Promise.resolve (async)_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110
utils.js:473 Object {msg: "failed lookup for https://satsrv04.researchstudio.…d/8630413039704447000 in utils.js:urisToLookupMap", error: Object, urisAsArray: Array[5], uris: Array[5]}(anonymous function) @ utils.js:473Promise.resolve (async)_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110
utils.js:473 Object {msg: "failed lookup for https://satsrv04.researchstudio.…d/3686072706669236000 in utils.js:urisToLookupMap", error: Object, urisAsArray: Array[5], uris: Array[5]}(anonymous function) @ utils.js:473Promise.resolve (async)_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110
utils.js:473 Object {msg: "failed lookup for https://satsrv04.researchstudio.…d/3645095385494221000 in utils.js:urisToLookupMap", error: Object, urisAsArray: Array[5], uris: Array[5]}(anonymous function) @ utils.js:473Promise.resolve (async)_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110
utils.js:473 Object {msg: "failed lookup for https://satsrv04.researchstudio.…d/1532447512392972300 in utils.js:urisToLookupMap", error: Object, urisAsArray: Array[5], uris: Array[5]}(anonymous function) @ utils.js:473Promise.resolve (async)_fulfilled @ q.js:789self.promiseDispatch.done @ q.js:818Promise.promise.promiseDispatch @ q.js:751(anonymous function) @ q.js:511flush @ q.js:110
configRedux.js:10 action:   initialPageLoad Object {ownNeeds: Object, connections: Object, events: Object, theirNeeds: Object}
configRedux.js:13 changing state from  Object {config: Object, router: Object, user: Object, messages: Object, lastUpdateTime: 1467897504738…}
configRedux.js:17 changed state to  Object {config: Object, router: Object, user: Object, messages: Object, lastUpdateTime: 1467897546524…}
undefined:1 Uncaught (in promise) Object {message: "Failed to fetch connection uris for need <https://…841000> because of:↵getNode: uri must not be null"}
undefined:1 Uncaught (in promise) Object {message: "Failed to fetch connection uris for need <https://…841000> because of:↵getNode: uri must not be null"}
undefined:1 Uncaught (in promise) Object {message: "Failed to fetch connection uris for need <https://…841000> because of:↵getNode: uri must not be null"}
undefined:1 Uncaught (in promise) Object {msg: "user needlist retrieval failed", error: Object}
```

on the owner-server:

```

15:17:05.172 [http-apr-8443-exec-55] INFO  w.owner.web.rest.RestNeedController - Getting all needs of user: 
15:17:45.495 [http-apr-8443-exec-58] INFO  w.owner.web.rest.RestNeedController - Getting all needs of user: 
15:18:08.462 [ActiveMQ Connection Executor: ssl://satsrv04.researchstudio.at/192.168.124.6:61617] WARN  o.s.j.c.CachingConnectionFactory - Encountered a JMSException - resetting the underlying JMS Connection
javax.jms.JMSException: Channel was inactive for too (>30000) long: tcp://192.168.124.6:61617
    at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:49) ~[activemq-client-5.8.0.jar:5.8.0]
    at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1969) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:1988) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.WireFormatNegotiator.onException(WireFormatNegotiator.java:160) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.AbstractInactivityMonitor.onException(AbstractInactivityMonitor.java:332) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.transport.AbstractInactivityMonitor$4.run(AbstractInactivityMonitor.java:233) ~[activemq-client-5.8.0.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: org.apache.activemq.transport.InactivityIOException: Channel was inactive for too (>30000) long: tcp://192.168.124.6:61617
    ... 4 common frames omitted
15:18:08.475 [Camel (wonOwnerCamel) thread #9 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.IllegalStateException: The Consumer is closed
    at org.apache.activemq.ActiveMQMessageConsumer.checkClosed(ActiveMQMessageConsumer.java:817) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQMessageConsumer.receive(ActiveMQMessageConsumer.java:581) ~[activemq-client-5.8.0.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveMessage(AbstractPollingMessageListenerContainer.java:413) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:293) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:18:08.475 [Camel (wonOwnerCamel) thread #9 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.DefaultJmsMessageListenerContainer - Setup of JMS message listener invoker failed for destination 'temporary' - trying to recover. Cause: The Consumer is closed
15:18:08.475 [Camel (wonOwnerCamel) thread #16 - JmsConsumer[OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e]] WARN  o.a.c.c.j.DefaultJmsMessageListenerContainer - Setup of JMS message listener invoker failed for destination 'OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e' - trying to recover. Cause: The Session is closed
15:18:24.729 [http-apr-8443-exec-55] INFO  w.owner.web.rest.RestNeedController - Getting all needs of user: 
15:19:00.844 [Camel (wonOwnerCamel) thread #9 - TemporaryQueueReplyManager[OwnerProtocol.in]] INFO  o.s.j.c.CachingConnectionFactory - Established shared JMS Connection: ActiveMQConnection {id=ID:SAT021-15098-1467889767100-1:2,clientId=null,started=false}
15:19:04.974 [Camel (wonOwnerCamel) thread #16 - JmsConsumer[OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e]] INFO  o.a.c.c.j.DefaultJmsMessageListenerContainer - Successfully refreshed JMS Connection
15:19:04.974 [Camel (wonOwnerCamel) thread #9 - TemporaryQueueReplyManager[OwnerProtocol.in]] INFO  o.a.c.c.j.DefaultJmsMessageListenerContainer - Successfully refreshed JMS Connection
15:19:04.986 [Camel (wonOwnerCamel) thread #10 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.IllegalStateException: The Session is closed
    at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:731) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQSession.getTransacted(ActiveMQSession.java:521) ~[activemq-client-5.8.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.springframework.jms.connection.CachingConnectionFactory$CachedSessionInvocationHandler.invoke(CachingConnectionFactory.java:384) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at com.sun.proxy.$Proxy181.getTransacted(Unknown Source) ~[na:na]
    at org.springframework.jms.listener.AbstractMessageListenerContainer.commitIfNecessary(AbstractMessageListenerContainer.java:696) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:341) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:19:04.992 [Camel (wonOwnerCamel) thread #13 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.IllegalStateException: The Session is closed
    at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:731) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQSession.getTransacted(ActiveMQSession.java:521) ~[activemq-client-5.8.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.springframework.jms.connection.CachingConnectionFactory$CachedSessionInvocationHandler.invoke(CachingConnectionFactory.java:384) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at com.sun.proxy.$Proxy181.getTransacted(Unknown Source) ~[na:na]
    at org.springframework.jms.listener.AbstractMessageListenerContainer.commitIfNecessary(AbstractMessageListenerContainer.java:696) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:341) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:19:04.993 [Camel (wonOwnerCamel) thread #11 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.IllegalStateException: The Session is closed
    at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:731) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQSession.getTransacted(ActiveMQSession.java:521) ~[activemq-client-5.8.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.springframework.jms.connection.CachingConnectionFactory$CachedSessionInvocationHandler.invoke(CachingConnectionFactory.java:384) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at com.sun.proxy.$Proxy181.getTransacted(Unknown Source) ~[na:na]
    at org.springframework.jms.listener.AbstractMessageListenerContainer.commitIfNecessary(AbstractMessageListenerContainer.java:696) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:341) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
15:19:04.994 [Camel (wonOwnerCamel) thread #12 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.IllegalStateException: The Session is closed
    at org.apache.activemq.ActiveMQSession.checkClosed(ActiveMQSession.java:731) ~[activemq-client-5.8.0.jar:na]
    at org.apache.activemq.ActiveMQSession.getTransacted(ActiveMQSession.java:521) ~[activemq-client-5.8.0.jar:na]
    at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source) ~[na:na]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45]
    at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45]
    at org.springframework.jms.connection.CachingConnectionFactory$CachedSessionInvocationHandler.invoke(CachingConnectionFactory.java:384) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
    at com.sun.proxy.$Proxy181.getTransacted(Unknown Source) ~[na:na]
    at org.springframework.jms.listener.AbstractMessageListenerContainer.commitIfNecessary(AbstractMessageListenerContainer.java:696) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:341) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) ~[spring-jms-4.1.1.RELEASE.jar:na]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

**Comment by quasarchimaere** [comment]
is this still an issue?

**Comment by fkleedorfer** [comment]
Well I have > 70 Needs in one of my accounts and this does not happen. I doubt this was causede by a much lower number.
