### ISSUE TITLE
GUI elements get corrupted sometimes

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#723]
See screenshot below

There is some error in the console  (dont know if its connected to this:)

app_jspm.bundle.js:29379 TypeError: Cannot read property 'get' of undefined
    at https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:21133:33
    at https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:96412:25
    at https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:98406:16
    at https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:96973:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate [as iterate](https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:97239:13)
    at src_Map__Map.__iterate (https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:96971:32)
    at src_Set__Set.__iterate (https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:98405:24)
    at SetIterable.filterSequence.__iterateUncached (https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:96411:18)
    at seqIterate (https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:95920:18)
    at SetIterable.Seq.__iterate (https://satsrv06.researchstudio.at/owner/generated/app_jspm.bundle.js:95683:14) <section ui-view="" class="ng-scope">

**Comment by heikofriedrich** [comment]
![gui](https://cloud.githubusercontent.com/assets/7766279/17518263/81ce0b9e-5e47-11e6-8212-b3a77b4c5289.png)

**Comment by heikofriedrich** [comment]
code js:

OverviewPostsController = function OverviewPostsController() {
                _classCallCheck(this, OverviewPostsController);

                attach(this, serviceDependencies, arguments);
                this.selection = 1;

                var selectFromState = function selectFromState(state) {
                    var unreadEvents = selectUnreadEvents(state);
                    var receivedHintEvents = unreadEvents.filter(function (e) {
                        return e.get('eventType') === won.EVENT.HINT_RECEIVED;
                    });

**Comment by m0ru** [comment]
Solution: change filter function to `e => e && e.get('eventType')  === won.EVENT.HINT_RECEIVED`.

**Comment by quasarchimaere** [comment]
since the code has changed after this ticket was created, could it be that this is a non-issue now? please recheck and close if necessary

**Comment by heikofriedrich** [comment]
i couldnt reproduce this anymore, so i will close the issue. we can reopen it if it occurs again

**Comment by heikofriedrich** [comment]
it occured again after creating couple of needs while switching the tabs (post overview, feed, matches, ...)
Errors from my console are: 

`
Uncaught (in promise) TypeError: c.get is not a function
    at app_jspm.bundle.js:879
    at app_jspm.bundle.js:94622
    at app_jspm.bundle.js:95183
    at ArrayMapNode.iterate.HashCollisionNode.iterate (app_jspm.bundle.js:95449)
    at src_Map__Map.__iterate (app_jspm.bundle.js:95181)
    at KeyedIterable.filterSequence.__iterateUncached (app_jspm.bundle.js:94621)
    at seqIterate (app_jspm.bundle.js:94130)
    at KeyedIterable.Seq.__iterate (app_jspm.bundle.js:93893)
    at KeyedIterable.forEach (app_jspm.bundle.js:97154)
    at app_jspm.bundle.js:95078
`

`Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at app_jspm.bundle.js:36271
    at app_jspm.bundle.js:94662
    at app_jspm.bundle.js:96616
    at app_jspm.bundle.js:95183
    at ArrayMapNode.iterate.HashCollisionNode.iterate (app_jspm.bundle.js:95449)
    at src_Map__Map.__iterate (app_jspm.bundle.js:95181)
    at src_Set__Set.__iterate (app_jspm.bundle.js:96615)
    at groupByFactory (app_jspm.bundle.js:94661)
    at src_Set__Set.groupBy (app_jspm.bundle.js:97276)
    at app_jspm.bundle.js:36270`

`TypeError: Cannot read property 'get' of undefined
    at app_jspm.bundle.js:36150
    at app_jspm.bundle.js:94662
    at app_jspm.bundle.js:96616
    at app_jspm.bundle.js:95183
    at ArrayMapNode.iterate.HashCollisionNode.iterate (app_jspm.bundle.js:95449)
    at src_Map__Map.__iterate (app_jspm.bundle.js:95181)
    at src_Set__Set.__iterate (app_jspm.bundle.js:96615)
    at groupByFactory (app_jspm.bundle.js:94661)
    at src_Set__Set.groupBy (app_jspm.bundle.js:97276)
    at groupByType (app_jspm.bundle.js:36149)`

`TypeError: Cannot read property 'get' of undefined
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:28360:33
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:94622:25
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:96616:16
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:95183:16
    at ArrayMapNode.iterate.HashCollisionNode.iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:95449:13)
    at src_Map__Map.__iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:95181:32)
    at src_Set__Set.__iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:96615:24)
    at SetIterable.filterSequence.__iterateUncached (https://www.matchat.org/owner/generated/app_jspm.bundle.js:94621:18)
    at seqIterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:94130:18)
    at SetIterable.Seq.__iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:93893:14) <section ui-view="" class="ng-scope">`

**Comment by quasarchimaere** [comment]
happened to me as well (also the same errormessage -> e.get from undefined

in code snippet:
var receivedHintEvents = unreadEvents.filter(function (e) {
                        return e.get('eventType') === won.EVENT.HINT_RECEIVED;
                    });

marking this issue as "prio:high" to emphasize the severity

**Comment by fkleedorfer** [comment]
Yep it's quite a recent regression bug, and a very important one to fix.

**Comment by heikofriedrich** [comment]
happend again on matchat now

**Comment by m0ru** [comment]
That will be a constant re-opener, as this means the javascript crashed *somewhere* and the templates fail to render. it's more of a symptom. More interesting is the error that you should be able to find in the console.

**Comment by heikofriedrich** [comment]
ok i will close this one then and link it to a new opened bug then
