### ISSUE TITLE
Wellformedness Checking

### ISSUE THREAD

**Issue by m0ru** [researchstudio-sat/webofneeds#730]
```
14:54:32.272 [Camel (wonOwnerCamel) thread #18 - JmsConsumer[OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e]] INFO  w.p.m.p.i.WellformednessCheckingWonMessageProcessor - Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true
 Offending message:
<https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#content-tmb0> {
    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx>
            <http://purl.org/webofneeds/model#hasTextMessage>
                    "WonMessageNotWellFormedException: Message is not valid, failed at check validation/05_sign/signature_chain.rq: SELECT query produced this binding: ( ?envChainSize = 1 ) ( ?parallelEnvSigChainSize = 1 ) ( ?contentChainSize = 1 ) ( ?parallelContentSigChainSize = 0 ) ( ?check = \"FAIL\" )"^^<http://www.w3.org/2001/XMLSchema#string> .
}

<https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#envelope-4cj8-sig> {
    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#envelope-4cj8-sig>
            a       <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#Signature> ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasSignatureValue>
                    "MGYCMQC9FTwIaGEQA/6jYHBHUPznsyeCrcu8ectKmlIbHTAtM5kQHjP7pFGiJfHTzGMUXwsCMQDxREHEWXp1bf9lnnS/VBN8W7Hca01mc2Li2EkMhP8GP1z87l4jNcfPyldQkSClBLU=" ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasVerificationCertificate>
                    <https://satsrv04.researchstudio.at:8889/won/resource> ;
            <http://purl.org/webofneeds/message#hasHash>
                    "AJ9nskpqVLzJ5PHhUa5M2lgPw6ooa4OWbowHoRWCbjV1W2WeGB7d4DBGwl8N7ewyNAb+Rj+nq9Ll2Fz3zpzvGbLon7MM/B91yWCjxQFOJpq7g634qC4ZkxfJrUA5L6DvXhDQEpHe1Ev3bACRT7Y+MKAun8T3HcrMI1kI+grt/0yt" ;
            <http://purl.org/webofneeds/message#hasPublicKeyFingerprint>
                    "5D/TjYc75Q1OIjcwd79InPUpYtqAmxy0oZGGS5bAego=" ;
            <http://purl.org/webofneeds/message#hasSignedGraph>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#envelope-4cj8> .
}

<https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#envelope-4cj8> {
    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx>
            a       <http://purl.org/webofneeds/message#FromSystem> ;
            <http://purl.org/webofneeds/message#hasContent>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#content-tmb0> ;
            <http://purl.org/webofneeds/message#hasMessageType>
                    <http://purl.org/webofneeds/message#FailureResponse> ;
            <http://purl.org/webofneeds/message#hasReceivedTimestamp>
                    "1470833673483"^^<http://www.w3.org/2001/XMLSchema#long> ;
            <http://purl.org/webofneeds/message#hasReceiverNeed>
                    <https://satsrv04.researchstudio.at:8889/won/resource/need/851633321127540700> ;
            <http://purl.org/webofneeds/message#hasReceiverNode>
                    <https://satsrv04.researchstudio.at:8889/won/resource> ;
            <http://purl.org/webofneeds/message#hasSenderNeed>
                    <https://satsrv04.researchstudio.at:8889/won/resource/need/851633321127540700> ;
            <http://purl.org/webofneeds/message#hasSenderNode>
                    <https://satsrv04.researchstudio.at:8889/won/resource> ;
            <http://purl.org/webofneeds/message#isResponseTo>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/2025518149756360700> ;
            <http://purl.org/webofneeds/message#isResponseToMessageType>
                    <http://purl.org/webofneeds/message#CreateMessage> ;
            <http://purl.org/webofneeds/message#protocolVersion>
                    "1.0"^^<http://www.w3.org/2001/XMLSchema#string> .
    
    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#envelope-4cj8>
            a       <http://purl.org/webofneeds/message#EnvelopeGraph> ;
            <http://purl.org/webofneeds/message#containsSignature>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#content-tmb0-sig> ;
            <http://www.w3.org/2004/03/trix/rdfg-1/subGraphOf>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx> .
    
    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#content-tmb0-sig>
            a       <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#Signature> ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasSignatureValue>
                    "MGUCMQDZWVkQsJXeDH+wIc9m7WoHmOsdabCoQeZYClhd1OEPD06NY/eWIJLUFT0iHtLm54gCMGjNho56Lk7aViB6IBMoUP1Hd9ukexH84SjPU+MMKh46R/XN9qT+jD1qtaob3G/RKA==" ;
            <http://icp.it-risk.iwvi.uni-koblenz.de/ontologies/signature.owl#hasVerificationCertificate>
                    <https://satsrv04.researchstudio.at:8889/won/resource> ;
            <http://purl.org/webofneeds/message#hasHash>
                    "BKeOvcZis3EyCRmNIXUMGfTO/UmggISR02VDHTrv7hEXsJ6WcDVQzLCx/s0GGs9K3DZhC3rOHBcuM04aroAf0g==" ;
            <http://purl.org/webofneeds/message#hasPublicKeyFingerprint>
                    "5D/TjYc75Q1OIjcwd79InPUpYtqAmxy0oZGGS5bAego=" ;
            <http://purl.org/webofneeds/message#hasSignedGraph>
                    <https://satsrv04.researchstudio.at:8889/won/resource/event/7705f7jw8sxhq9oau9qx#content-tmb0> .
}

14:54:32.285 [Camel (wonOwnerCamel) thread #18 - JmsConsumer[OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e]] ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID:d2bab8aae357-53217-1470829661465-3:70:1:1:1 on ExchangeId: ID-SAT021-21086-1470833506907-0-15). Exhausted after delivery attempt: 1 caught: won.protocol.message.processor.exception.WonMessageNotWellFormedException: Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[Node2OwnerRouteact] [Node2OwnerRouteact] [activemqsslsatsrv04.researchstudio.at61617://queue:OwnerProtocol.Out.65e342886] [       130]
[Node2OwnerRouteact] [to2               ] [bean:wonMessageIntoCamelProcessor                                             ] [        27]
[Node2OwnerRouteact] [to3               ] [bean:wellformednessChecker                                                    ] [       102]

Exchange
---------------------------------------------------------------------------------------------------------------------------------------
Exchange[
	Id                  ID-SAT021-21086-1470833506907-0-15
	ExchangePattern     InOnly
	Headers             {breadcrumbId=ID-d2bab8aae357-58703-1470829654218-0-489, CamelRedelivered=false, CamelRedeliveryCounter=0, JMSCorrelationID=null, JMSDeliveryMode=2, JMSDestination=queue://OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e, JMSExpiration=0, JMSMessageID=ID:d2bab8aae357-53217-1470829661465-3:70:1:1:1, JMSPriority=4, JMSRedelivered=false, JMSReplyTo=null, JMSTimestamp=1470833673545, JMSType=null, JMSXGroupID=null, JMSXUserID=null, wonMessage=won.protocol.message.WonMessage@69b5bcbe, wonMessageType=http://purl.org/webofneeds/message#FailureResponse}
	BodyType            null
	Body                [Body is null]
]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
won.protocol.message.processor.exception.WonMessageNotWellFormedException: Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true
	at won.protocol.message.processor.impl.WellformednessCheckingWonMessageProcessor.process(WellformednessCheckingWonMessageProcessor.java:55) ~[won-core-0.2-SNAPSHOT.jar:na]
	at won.protocol.message.processor.camel.WonMessageProcessorCamelAdapter.process(WonMessageProcessorCamelAdapter.java:51) ~[won-core-0.2-SNAPSHOT.jar:na]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:97) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) [camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:67) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint.onExchange(ProcessorEndpoint.java:103) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:na]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) [camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) [camel-core-2.12.1.jar:na]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103) [camel-jms-2.12.1.jar:2.12.1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:685) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:623) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:591) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:308) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) [spring-jms-4.1.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
14:54:32.333 [Camel (wonOwnerCamel) thread #18 - JmsConsumer[OwnerProtocol.Out.65e342886ba5a1a9c2ca46339aa37709d5a08edb9aaaf7af5e02be9e]] WARN  o.a.c.c.jms.EndpointMessageListener - Execution of JMS message listener failed. Caused by: [org.apache.camel.RuntimeCamelException - won.protocol.message.processor.exception.WonMessageNotWellFormedException: Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true]
org.apache.camel.RuntimeCamelException: won.protocol.message.processor.exception.WonMessageNotWellFormedException: Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true
	at org.apache.camel.util.ObjectHelper.wrapRuntimeCamelException(ObjectHelper.java:1344) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.jms.EndpointMessageListener$EndpointMessageListenerAsyncCallback.done(EndpointMessageListener.java:186) ~[camel-jms-2.12.1.jar:2.12.1]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:107) ~[camel-jms-2.12.1.jar:2.12.1]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:685) ~[spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:623) ~[spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:591) ~[spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:308) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:246) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1142) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1134) [spring-jms-4.1.1.RELEASE.jar:na]
	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1031) [spring-jms-4.1.1.RELEASE.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_45]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
Caused by: won.protocol.message.processor.exception.WonMessageNotWellFormedException: Message is not valid, failed at check validation/02_prop/invalid_direction.rq: ASK query returned true
	at won.protocol.message.processor.impl.WellformednessCheckingWonMessageProcessor.process(WellformednessCheckingWonMessageProcessor.java:55) ~[won-core-0.2-SNAPSHOT.jar:na]
	at won.protocol.message.processor.camel.WonMessageProcessorCamelAdapter.process(WonMessageProcessorCamelAdapter.java:51) ~[won-core-0.2-SNAPSHOT.jar:na]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:97) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.component.bean.BeanProcessor.process(BeanProcessor.java:67) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint.onExchange(ProcessorEndpoint.java:103) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:110) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.util.AsyncProcessorHelper.process(AsyncProcessorHelper.java:105) ~[camel-core-2.12.1.jar:2.12.1]
	at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:87) ~[camel-core-2.12.1.jar:na]
	at org.apache.camel.component.jms.EndpointMessageListener.onMessage(EndpointMessageListener.java:103) ~[camel-jms-2.12.1.jar:2.12.1]
	... 11 common frames omitted
```

**Comment by m0ru** [comment]
Solved this by pulling from master. Apparantly a newer node-version already had been deployed on satsrv.
