### ISSUE TITLE
use let's encrypt on WoN node and owner

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#758]
Automatically obtain certificates for the servers

**Comment by heikofriedrich** [comment]
trying first: installing lets encrypt certbot manually on our docker nginx image (debian jessie) https://certbot.eff.org/#debianjessie-nginx

**Comment by heikofriedrich** [comment]
for automation and docker images two options:
1) build an independet letsencrypt certbot docker image with standalone server to create (and renew) certificates , that are mounted then into the nginx container
2) build an image including nginx and letsencrypt certbot to use the certificates there and be able to create renew them without stoping the server. add a cron job for automatic renewel of certificates

=> options 2) seems better since the server does not need to be stopped for certificate renewal, however the container probably needs to be restarted (?) manually (?) to use the new certificates after automatic renewal => test this

**Comment by heikofriedrich** [comment]
solution now this this:
* independet nginx and letsnecrypt docker containers
* letsencrypt docker container starts cron job to request/renew ssl certificate and maps them out to a volume on the host
* from there it is mounted into the nginx container
* nginx container can be started with two configurations: 
1) http-only: this is used for bootstrap when no ssl certificate is there yet so we can startup a webserver anyway
2) default: with ssl letsencrypt certificates

**Comment by heikofriedrich** [comment]
Currently there is still a probelm if trying to (force/dry-run) renew the certificate:

docker -H satcluster02:2375 exec letsencrypt certbot certonly --webroot -w /usr/share/nginx/html -d www.matchat.org --email florian.kleedorfer@researchstudio.at -t --noninteractive --agree-tos --force-renew

=> 

2016-08-25 15:49:57,276:ERROR:certbot.crypto_util:[('PEM routines', 'PEM_read_bio', 'no start line')]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 258, in _load_cert_or_req
    return load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
An unexpected error occurred:
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
Please see the logfiles in /var/log/letsencrypt for more details.
root@692cb944eb71:/# cat /var/log/letsencrypt/letsencrypt.log
2016-08-25 15:49:51,412:DEBUG:certbot.main:Root logging level set at 30
2016-08-25 15:49:51,413:INFO:certbot.main:Saving debug log to /var/log/letsencrypt/letsencrypt.log
2016-08-25 15:49:51,414:DEBUG:certbot.main:certbot version: 0.8.1
2016-08-25 15:49:51,414:DEBUG:certbot.main:Arguments: ['--webroot', '-w', '/usr/share/nginx/html', '-d', 'www.matchat.org', '--email', 'florian.kleedorfer@researchstudio.at', '-t', '--noninteractive', '--agree-tos']
2016-08-25 15:49:51,415:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#webroot,PluginEntryPoint#null,PluginEntryPoint#manual,PluginEntryPoint#standalone)
2016-08-25 15:49:51,415:DEBUG:certbot.plugins.selection:Requested authenticator webroot and installer None
2016-08-25 15:49:51,421:DEBUG:certbot.plugins.selection:Single candidate plugin: * webroot
Description: Place files in webroot directory
Interfaces: IAuthenticator, IPlugin
Entry point: webroot = certbot.plugins.webroot:Authenticator
Initialized: <certbot.plugins.webroot.Authenticator object at 0x7f51b3758b10>
Prep: True
2016-08-25 15:49:51,422:DEBUG:certbot.plugins.selection:Selected authenticator <certbot.plugins.webroot.Authenticator object at 0x7f51b3758b10> and installer None
2016-08-25 15:49:51,971:DEBUG:certbot.main:Picked account: <Account(d8fd9f301a6b812bb394f61ceed5b980)>
2016-08-25 15:49:51,973:DEBUG:root:Sending GET request to https://acme-v01.api.letsencrypt.org/directory. args: (), kwargs: {}
2016-08-25 15:49:51,979:INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
2016-08-25 15:49:57,272:DEBUG:requests.packages.urllib3.connectionpool:"GET /directory HTTP/1.1" 200 280
2016-08-25 15:49:57,273:DEBUG:root:Received <Response [200]>. Headers: {'Content-Length': '280', 'Expires': 'Thu, 25 Aug 2016 15:49:54 GMT', 'Boulder-Request-Id': 'f3OV8GrKJ4s6jGHYCLZm0v9MrwOZkVvnPBopMde6bp4', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 25 Aug 2016 15:49:54 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'KUD0gLiL8fMYh8aR9XVNhdw2HXJ4We2L0MWt_GIoAf4'}. Content: '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-08-25 15:49:57,274:DEBUG:acme.client:Received response <Response [200]> (headers: {'Content-Length': '280', 'Expires': 'Thu, 25 Aug 2016 15:49:54 GMT', 'Boulder-Request-Id': 'f3OV8GrKJ4s6jGHYCLZm0v9MrwOZkVvnPBopMde6bp4', 'Strict-Transport-Security': 'max-age=604800', 'Server': 'nginx', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Date': 'Thu, 25 Aug 2016 15:49:54 GMT', 'X-Frame-Options': 'DENY', 'Content-Type': 'application/json', 'Replay-Nonce': 'KUD0gLiL8fMYh8aR9XVNhdw2HXJ4We2L0MWt_GIoAf4'}): '{\n  "new-authz": "https://acme-v01.api.letsencrypt.org/acme/new-authz",\n  "new-cert": "https://acme-v01.api.letsencrypt.org/acme/new-cert",\n  "new-reg": "https://acme-v01.api.letsencrypt.org/acme/new-reg",\n  "revoke-cert": "https://acme-v01.api.letsencrypt.org/acme/revoke-cert"\n}'
2016-08-25 15:49:57,276:ERROR:certbot.crypto_util:[('PEM routines', 'PEM_read_bio', 'no start line')]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 258, in _load_cert_or_req
    return load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]
2016-08-25 15:49:57,279:DEBUG:certbot.main:Exiting abnormally:
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 744, in main
    return config.func(config, plugins)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 555, in obtain_cert
    _, action = _auth_from_domains(le_client, config, domains, lineage)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 77, in _auth_from_domains
    action, lineage = _treat_as_renewal(config, domains)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 213, in _treat_as_renewal
    ident_names_cert, subset_names_cert = _find_duplicative_certs(config, domains)
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 244, in _find_duplicative_certs
    candidate_names = set(candidate_lineage.names())
  File "/usr/lib/python2.7/dist-packages/certbot/storage.py", line 598, in names
    return crypto_util.get_names_from_cert(f.read())
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 322, in get_names_from_cert
    csr, OpenSSL.crypto.load_certificate, typ)
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 300, in _get_names_from_cert_or_req
    loaded_cert_or_req = _load_cert_or_req(cert_or_req, load_func, typ)
  File "/usr/lib/python2.7/dist-packages/certbot/crypto_util.py", line 258, in _load_cert_or_req
    return load_func(typ, cert_or_req_str)
  File "/usr/lib/python2.7/dist-packages/OpenSSL/crypto.py", line 1608, in load_certificate
    _raise_current_error()
  File "/usr/lib/python2.7/dist-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
Error: [('PEM routines', 'PEM_read_bio', 'no start line')]

**Comment by heikofriedrich** [comment]
- renew to new directory works 
- also doesnt work with http_only_server running and same directory => check certs dir access rights => doesnt seem to be the problem
- also doesnt work (other error) with other cert directory and nginx server (not http_only) ??

- using new cert dir, restarting nginx, still able to execute renew? => caused the problem then ??
	=> try delete all folders and repeat whole deployment process
	=> now the error seems not to occur anymore until now, also --force-renew seemed to work => check again tomorrow

**Comment by heikofriedrich** [comment]
looks fine now, create pull request
