### ISSUE TITLE
cert mixup

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#774]
Something went wrong when installing the new certificates. This is the log output on the live owner app server

```
26.8.16 16:39:34.043 [Camel (wonOwnerCamel) thread #13 - TemporaryQueueReplyManager[OwnerProtocol.in]] WARN  o.a.c.c.j.r.TemporaryQueueReplyManager - Exception inside the DMLC for Temporary ReplyTo Queue for destination OwnerProtocol.in, refreshing ReplyTo destination
javax.jms.JMSException: Could not connect to broker URL: ssl://www.matchat.org:61617. Reason: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:35) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:293) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:238) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:184) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:351) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:295) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:227) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:413) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.refreshSharedConnection(AbstractJmsListeningContainer.java:398) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.refreshConnectionUntilSuccessful(DefaultMessageListenerContainer.java:907) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.recoverAfterListenerSetupFailure(DefaultMessageListenerContainer.java:882) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1053) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[na:1.8.0_66-internal]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpBufferedOutputStream.flush(TcpBufferedOutputStream.java:115) ~[activemq-client-5.8.0.jar:5.8.0]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpTransport.oneway(TcpTransport.java:176) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.doOnewaySend(AbstractInactivityMonitor.java:322) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.oneway(AbstractInactivityMonitor.java:304) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:168) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:84) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:74) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:273) ~[activemq-client-5.8.0.jar:5.8.0]
        ... 12 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352) ~[na:1.8.0_66-internal]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260) ~[na:1.8.0_66-internal]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105) ~[na:1.8.0_66-internal]
        at won.cryptography.ssl.TrustManagerWrapperWithTrustService.checkServerTrusted(TrustManagerWrapperWithTrustService.java:55) ~[won-core-0.2-SNAPSHOT.jar:na]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:922) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_66-internal]
        ... 30 common frames omitted
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
        at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:153) ~[na:1.8.0_66-internal]
        at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79) ~[na:1.8.0_66-internal]
        at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[na:1.8.0_66-internal]
        at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347) ~[na:1.8.0_66-internal]
        ... 38 common frames omitted
26.8.16 16:39:34.044 [Camel (wonOwnerCamel) thread #13 - TemporaryQueueReplyManager[OwnerProtocol.in]] ERROR o.a.c.c.j.DefaultJmsMessageListenerContainer - Could not refresh JMS Connection for destination 'temporary' - retrying using FixedBackOff{interval=5000, currentAttempts=253, maxAttempts=unlimited}. Cause: Could not connect to broker URL: ssl://www.matchat.org:61617. Reason: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
```

**Comment by heikofriedrich** [comment]
Cause of the problem:

* At startup owner registers (RegistrationRestClientHttps.register) with the default wonnode which it reaches over www.matchat.org => it receives the public letsencrypt certificate and saves the wonnode in its trust store (and trusts that wonnode with that certificate from now on => TOFU strategy)
* Shortly later the owner tries to connect to the wonnode JMS broker, in this ssl handshake the wonnode sends its (local) self signed certificate to the owner which is different from the public letsenrcrypt certificate that lies on the nginx server
* These two certificates for the same wonnode on the owner dont match and the above exception is thrown

How to fix:
* we need the same letsencrypt certificate on the nginx as well as on the wonnde 
* therefore our current solution is to move the wonnode docker container with its postgres database (after separation from owner database) to satcluster02 where the nginx is to avoid to copy the letsencrypt certificate from satscluster02 to satcluster01. Owner and matcher containers remain on satcluster01

**Comment by heikofriedrich** [comment]
dis as described, now wonnode uses letsencrypt certificate, owner (matcher??) still uses self signed certificate. now we have a new error in wonnode:

31.8.16 08:55:30.582 [ActiveMQ Transport: ssl:///192.168.120.125:50594] WARN  o.a.a.b.T.Transport - Transport Connection to: tcp://192.168.120.125:50594 failed: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
31.8.16 08:55:30.589 [ActiveMQ BrokerService[wonBroker] Task-9] ERROR o.a.a.broker.TransportConnector - Could not accept connection from tcp://192.168.120.125:50594: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown

and in owner: 
javax.jms.JMSException: Could not connect to broker URL: ssl://www.matchat.org:61616. Reason: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:35) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:293) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:238) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createConnection(ActiveMQConnectionFactory.java:184) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.springframework.jms.connection.SingleConnectionFactory.doCreateConnection(SingleConnectionFactory.java:351) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.initConnection(SingleConnectionFactory.java:295) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.connection.SingleConnectionFactory.createConnection(SingleConnectionFactory.java:227) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180) ~[spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.createSharedConnection(AbstractJmsListeningContainer.java:413) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.establishSharedConnection(AbstractJmsListeningContainer.java:381) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.establishSharedConnection(DefaultMessageListenerContainer.java:786) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.doStart(AbstractJmsListeningContainer.java:285) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.AbstractJmsListeningContainer.start(AbstractJmsListeningContainer.java:270) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.springframework.jms.listener.DefaultMessageListenerContainer.start(DefaultMessageListenerContainer.java:587) [spring-jms-4.1.1.RELEASE.jar:4.1.1.RELEASE]
        at org.apache.camel.component.jms.reply.ReplyManagerSupport.doStart(ReplyManagerSupport.java:229) [camel-jms-2.12.1.jar:2.12.1]
        at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:65) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.util.ServiceHelper.startService(ServiceHelper.java:54) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.jms.JmsProducer.createReplyManager(JmsProducer.java:516) [camel-jms-2.12.1.jar:2.12.1]
        at org.apache.camel.component.jms.JmsProducer.initReplyManager(JmsProducer.java:103) [camel-jms-2.12.1.jar:2.12.1]
        at org.apache.camel.component.jms.JmsProducer.processInOut(JmsProducer.java:177) [camel-jms-2.12.1.jar:2.12.1]
        at org.apache.camel.component.jms.JmsProducer.process(JmsProducer.java:142) [camel-jms-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:573) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:506) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:215) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RecipientList.sendToRecipientList(RecipientList.java:153) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RecipientList.process(RecipientList.java:112) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:118) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:80) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.ChoiceProcessor.process(ChoiceProcessor.java:103) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:72) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:398) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:191) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.seda.SedaConsumer.sendToConsumers(SedaConsumer.java:291) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.seda.SedaConsumer.doRun(SedaConsumer.java:200) [camel-core-2.12.1.jar:2.12.1]
        at org.apache.camel.component.seda.SedaConsumer.run(SedaConsumer.java:147) [camel-core-2.12.1.jar:2.12.1]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66-internal]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66-internal]
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[na:1.8.0_66-internal]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[na:1.8.0_66-internal]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[na:1.8.0_66-internal]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpBufferedOutputStream.flush(TcpBufferedOutputStream.java:115) ~[activemq-client-5.8.0.jar:5.8.0]
        at java.io.DataOutputStream.flush(DataOutputStream.java:123) ~[na:1.8.0_66-internal]
        at org.apache.activemq.transport.tcp.TcpTransport.oneway(TcpTransport.java:176) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.doOnewaySend(AbstractInactivityMonitor.java:322) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.AbstractInactivityMonitor.oneway(AbstractInactivityMonitor.java:304) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:168) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.sendWireFormat(WireFormatNegotiator.java:84) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:74) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58) ~[activemq-client-5.8.0.jar:5.8.0]
        at org.apache.activemq.ActiveMQConnectionFactory.createActiveMQConnection(ActiveMQConnectionFactory.java:273) ~[activemq-client-5.8.0.jar:5.8.0]
        ... 43 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_66-internal]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_66-internal]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_66-internal]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105) ~[na:1.8.0_66-internal]
        at won.cryptography.ssl.TrustManagerWrapperWithTrustService.checkServerTrusted(TrustManagerWrapperWithTrustService.java:55) ~[won-core-0.2-SNAPSHOT.jar:na]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:922) ~[na:1.8.0_66-internal]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[na:1.8.0_66-internal]
        ... 61 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146) ~[na:1.8.0_66-internal]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[na:1.8.0_66-internal]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_66-internal]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[na:1.8.0_66-internal]
        ... 69 common frames omitted

and in matcher:
31.8.16 08:55:23.735 [Camel (ClusterSystem) thread #0 - JmsConsumer[MatcherProtocol.Out.Need]] ERROR o.a.c.c.j.DefaultJmsMessageListenerContainer - Could not refresh JMS Connection for destination 'MatcherProtocol.Out.Need' - retrying using FixedBackOff{interval=5000, currentAttempts=43, maxAttempts=unlimited}. Cause: Could not connect to broker URL: ssl://www.matchat.org:61616. Reason: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by heikofriedrich** [comment]
is letsencrypt not among the trusted certificates in oracle jdk? https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/26

**Comment by heikofriedrich** [comment]
activated ssl debug logging in wonnode and owner (-Djavax.net.debug=ssl):

seems like the owner adds the wonnode certificate to its trusted certificates:
```
adding as trusted cert:
  Subject: CN=www.matchat.org
  Issuer:  CN=Let's Encrypt Authority X3, O=Let's Encrypt, C=US
  Algorithm: RSA; Serial number: 0x3884de42cc5c51abb21707206e8ebd6ee06
  Valid from Wed Aug 24 08:53:00 UTC 2016 until Tue Nov 22 08:53:00 UTC 2016
```

and also the wonnode seems to add the self signed certificates from the owner:
```
adding as trusted cert:
  Subject: OU=Web of Needs, CN=https://www.matchat.org/owner
  Issuer:  OU=Web of Needs, CN=https://www.matchat.org/owner
  Algorithm: EC; Serial number: 0x1
  Valid from Tue Aug 30 00:00:00 UTC 2016 until Fri Aug 31 00:00:00 UTC 2018
```

**Comment by heikofriedrich** [comment]
probelm was the following:

there were two versions of the letsencryptcertificate used (found by different validity dates). the nginx container had an older version (since this was not updated by the build process) than the wonnode.

problem was debugged in owner method TrustManagerWrapperWithTrustService.checkServerTrusted()

it had another version of the certificate in it trust store (received from nginx after register) than it received from the wonnode for the jms connection establishment
