### ISSUE TITLE
matches views are broken

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#829]
when receiving matches, open the global and per need matches views. Both are broken. See screenshots

`
angular.js:5343 TypeError: Cannot read property 'hasConnectionState' of undefined
    at matches.js:127
    at immutable.js:1249
    at List.__iterate (immutable.js:2758)
    at IndexedIterable.filterSequence.__iterateUncached (immutable.js:1248)
    at seqIterate (immutable.js:608)
    at IndexedIterable.IndexedSeq.__iterate (immutable.js:323)
    at IndexedIterable.forEach (immutable.js:4358)
    at immutable.js:2625
    at List.src_Map__Map.withMutations (immutable.js:1918)
    at new List (immutable.js:2622)(anonymous function) @ angular.js:5343
configRedux.js:10action:   @@reduxUiRouter/$stateChangeStart Object
`

`
angular.js:5343TypeError: Cannot read property 'hasConnectionState' of undefined
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:30760:52
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:104294:25
    at List.__iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:105515:13)
    at IndexedIterable.filterSequence.__iterateUncached (https://www.matchat.org/owner/generated/app_jspm.bundle.js:104293:18)
    at seqIterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:103802:18)
    at IndexedIterable.IndexedSeq.__iterate (https://www.matchat.org/owner/generated/app_jspm.bundle.js:103591:14)
    at IndexedIterable.forEach (https://www.matchat.org/owner/generated/app_jspm.bundle.js:106826:21)
    at https://www.matchat.org/owner/generated/app_jspm.bundle.js:105413:14
    at List.src_Map__Map.withMutations (https://www.matchat.org/owner/generated/app_jspm.bundle.js:104835:7)
    at new List (https://www.matchat.org/owner/generated/app_jspm.bundle.js:105411:20) <section ui-view="" class="ng-scope">
`

**Comment by heikofriedrich** [comment]
![matches](https://cloud.githubusercontent.com/assets/7766279/18754934/9f2473de-80ea-11e6-930e-17fc999514e8.png)

**Comment by heikofriedrich** [comment]
global matches view is empty

**Comment by fkleedorfer** [comment]
#827 seems to have only moved the bug elsewhere

**Comment by quasarchimaere** [comment]
should be fixed with pull request #830
