### ISSUE TITLE
User gets kicked out by owner application

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#834]
Sometimes a users gets kicked out of the application and is routed to the start page when trying to create a new need. => Unauthorized

`
configRouting.js:165 GET https://satsrv07.researchstudio.at/owner/rest/users/isSignedIn 401 (Unauthorized)accessControl @ configRouting.js:165(anonymous function) @ configRouting.js:88$broadcast @ angular.js:7889transitionTo @ angular-ui-router.js:1512go @ angular-ui-router.js:1421(anonymous function) @ router-middleware.js:14dispatch @ applyMiddleware.js:35(anonymous function) @ account-actions.js:75
utils.js:370 Uncaught (in promise) Error: Unauthorized(…)checkHttpStatus @ utils.js:370
messaging-agent.js:73 checking heartbeat presence:  22
`

Maybe related log in owner log:

`
27.9.16 15:43:49.476 [Thread-10] WARN  w.o.m.OwnerWonMessageSenderJMSBased - Could not register with default won node https://satsrv07.researchstudio.at/won/resource
java.lang.NullPointerException: null
        at won.protocol.util.RdfUtils.getNodeForPropertyPath(RdfUtils.java:663) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils$4.visit(RdfUtils.java:682) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils$4.visit(RdfUtils.java:679) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils.findFirst(RdfUtils.java:860) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils.findFirst(RdfUtils.java:867) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils.getNodeForPropertyPath(RdfUtils.java:678) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.util.RdfUtils.getURIPropertyForPropertyPath(RdfUtils.java:465) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.protocol.jms.ActiveMQServiceImpl.getBrokerEndpoint(ActiveMQServiceImpl.java:134) ~[won-core-0.2-SNAPSHOT.jar:na]
        at won.owner.messaging.OwnerProtocolCommunicationServiceImpl.configureCamelEndpoint(OwnerProtocolCommunicationServiceImpl.java:153) ~[won-owner-0.2-SNAPSHOT.jar:na]
        at won.owner.messaging.OwnerProtocolCommunicationServiceImpl.register(OwnerProtocolCommunicationServiceImpl.java:89) ~[won-owner-0.2-SNAPSHOT.jar:na]
`

After a restart of the owner things are working normal again ...
=> Is the reason that the registration at the wonnode was working then? (Exception didnt occur anymore)

**Comment by heikofriedrich** [comment]
in the browser i see this:

configRouting.js:165 GET https://satsrv06.researchstudio.at/owner/rest/users/isSignedIn 401 (Unauthorized)accessControl @ configRouting.js:165(anonymous function) @ configRouting.js:88$broadcast @ angular.js:7889transitionTo @ angular-ui-router.js:1512go @ angular-ui-router.js:1421(anonymous function) @ router-middleware.js:14dispatch @ applyMiddleware.js:35(anonymous function) @ account-actions.js:75
utils.js:370 Uncaught (in promise) Error: Unauthorized(…)checkHttpStatus @ utils.js:370

**Comment by heikofriedrich** [comment]
does this happen only on owner applications behind a proxy?

**Comment by fkleedorfer** [comment]
related to #821 ?

**Comment by m0ru** [comment]
The stack trace from above but with line-breaks:
```
configRouting.js:165 
GET https://satsrv06.researchstudio.at/owner/rest/users/isSignedIn 401 (Unauthorized)
accessControl @ configRouting.js:165
(anonymous function) @ configRouting.js:88
$broadcast @ angular.js:7889
transitionTo @ angular-ui-router.js:1512
go @ angular-ui-router.js:1421
(anonymous function) @ router-middleware.js:14
dispatch @ applyMiddleware.js:35
(anonymous function) @ account-actions.js:75
utils.js:370 
Uncaught (in promise) Error: Unauthorized(…)
checkHttpStatus @ utils.js:370
```

**Comment by heikofriedrich** [comment]
didnt have this problem for long time anymore => close this ticket?

**Comment by fkleedorfer** [comment]
yes, i agree
