### ISSUE TITLE
need becomes a zombie if keystore is deleted on server

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/webofneeds#901]
The key for signing any message on behalf of the need is lost when we delete the owner's keystore. This exception is found in the logs: 
```
Caused by: won.protocol.message.processor.exception.WonMessageProcessingException: Failed to sign message https://node.matchat.org/won/resource/event/6490691551601738000
        at won.protocol.message.processor.impl.SignatureAddingWonMessageProcessor.processOnBehalfOfNeed(SignatureAddingWonMessageProcessor.java:51) ~[won-cryptography-0.2-SNAPSHOT.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.doSigningOnOwner(OwnerWonMessageSenderJMSBased.java:122) ~[won-owner-0.2-SNAPSHOT.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:74) ~[won-owner-0.2-SNAPSHOT.jar:na]
        ... 29 common frames omitted
22.11.16 16:20:23.708 [http-apr-8443-exec-21] WARN  w.c.service.KeyStoreService - No certificate found for alias https://node.matchat.org/won/resource/need/8730609845216805000
```

Possible solution: use separate keystores for server keys and need keys - or do not use keystores for needs at all, also in order to alleviate possible concurency issues.

**Comment by fkleedorfer** [comment]
Fixed
