### ISSUE TITLE
exception reading truststore client jks file with keytool

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#940]
- why can the local client trust store not be read by keytool?
- bouncy castle libraries have been copied to the host

root@satvm01:/home/won/matchat/won-client-certs/wonnode# keytool -list -v -storetype UBER -providerclass org.bouncycastle.jce.provider.BouncyCastleProvider -keystore node-trusted-certs.jks
keytool error: java.io.IOException: javax.crypto.BadPaddingException: pad block corrupted
java.io.IOException: javax.crypto.BadPaddingException: pad block corrupted
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:121)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:239)
        at org.bouncycastle.crypto.io.DigestInputStream.read(Unknown Source)
        at java.io.DataInputStream.readFully(DataInputStream.java:195)
        at java.io.DataInputStream.readUTF(DataInputStream.java:609)
        at java.io.DataInputStream.readUTF(DataInputStream.java:564)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.loadStore(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BouncyCastleStore.engineLoad(Unknown Source)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at sun.security.tools.keytool.Main.doCommands(Main.java:795)
        at sun.security.tools.keytool.Main.run(Main.java:343)
        at sun.security.tools.keytool.Main.main(Main.java:336)
Caused by: javax.crypto.BadPaddingException: pad block corrupted
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher$BufferedGenericBlockCipher.doFinal(Unknown Source)
        at org.bouncycastle.jcajce.provider.symmetric.util.BaseBlockCipher.engineDoFinal(Unknown Source)
        at javax.crypto.Cipher.doFinal(Cipher.java:2048)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:118)
        ... 11 more

**Comment by heikofriedrich** [comment]
password was missing, here is the right command with password (temp):

keytool -list -v -storetype UBER -providerclass org.bouncycastle.jce.provider.BouncyCastleProvider -storepass temp -keystore node-trusted-certs.jks
