### ISSUE TITLE
debug bot exception while trying to register with wonnode

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#946]
* restart of bot seems to solve the connection problem => maybe bot starts up before won node is there and cannot properly connect then?
* check also other bots for this bug

``
20.1.17 16:41:59.742 [Thread-12] INFO  w.o.m.OwnerWonMessageSenderJMSBased - register at default won node https://node.matchat.org/won/resource
20.1.17 16:41:59.834 [Thread-11] INFO  w.o.m.OwnerProtocolCommunicationServiceImpl - we're not yet registered. Registering with WoN node:https://node.matchat.org/won/resource
20.1.17 16:42:00.095 [Thread-11] INFO  won.cryptography.ssl.TOFUStrategy - Certificate for 
4956f0246efe526c3230bc6908118da886c6fd1c70f6e754e9974ddd is added based on TOFU and from now on it is trusted!
20.1.17 16:42:09.693 [Thread-14] INFO  w.o.m.OwnerWonMessageSenderJMSBased - register at default won node https://node.matchat.org/won/resource
20.1.17 16:42:10.171 [Thread-11] WARN  w.o.m.OwnerWonMessageSenderJMSBased - Could not register with default won node https://node.matchat.org/won/resource. Try again later ... (reason is logged at loglevel 'DEBUG')
20.1.17 16:42:10.172 [Thread-14] INFO  w.o.m.OwnerProtocolCommunicationServiceImpl - setting up communication with won node: https://node.matchat.org/won/resource
20.1.17 16:42:10.185 [Thread-14] INFO  w.o.m.OwnerProtocolCommunicationServiceImpl - we're not yet registered. Registering with WoN node:https://node.matchat.org/won/resource
20.1.17 16:42:19.692 [Thread-15] INFO  w.o.m.OwnerWonMessageSenderJMSBased - register at default won node https://node.matchat.org/won/resource
20.1.17 16:42:20.242 [Thread-12] INFO  w.o.m.OwnerProtocolCommunicationServiceImpl - setting up communication with won node: https://node.matchat.org/won/resource
20.1.17 16:42:20.242 [Thread-14] WARN  w.o.m.OwnerWonMessageSenderJMSBased - Could not register with default won node https://node.matchat.org/won/resource. Try again later ... (reason is logged at loglevel 'DEBUG')
20.1.17 16:42:20.245 [Thread-12] INFO  w.o.m.OwnerProtocolCommunicationServiceImpl - we're not yet registered. Registering with WoN node:https://node.matchat.org/won/resource
20.1.17 16:42:27.227 [Thread-13] WARN  w.m.p.i.MatcherProtocolMatcherServiceImplJMSBased - Could not get topic lists from won node https://node.matchat.org/won/resource
java.lang.IllegalArgumentException: caught a clientHandler exception, which may indicate that the URI that was accessed isn't a linked data URI, please check https://node.matchat.org/won/resource. Underlying error message is: I/O error on GET request for "https://node.matchat.org/won/resource":Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
        at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:118) ~[bots.jar:na]
        at won.protocol.rest.LinkedDataRestClientHttps.readResourceDataWithHeaders(LinkedDataRestClientHttps.java:134) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.fetch(CachingLinkedDataSource.java:341) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchWithEtagValidation(CachingLinkedDataSource.java:298) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchAndCacheIfAppropriate(CachingLinkedDataSource.java:235) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchOnlyOnce(CachingLinkedDataSource.java:217) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.fetchOrUseCached(CachingLinkedDataSource.java:164) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:108) ~[bots.jar:na]
        at won.protocol.util.linkeddata.CachingLinkedDataSource.getDataForResource(CachingLinkedDataSource.java:429) ~[bots.jar:na]
        at won.protocol.jms.MatcherActiveMQServiceImpl.getMatcherProtocolTopicNamesWithResource(MatcherActiveMQServiceImpl.java:71) ~[bots.jar:na]
        at won.matcher.protocol.impl.MatcherProtocolCommunicationServiceImpl.getMatcherProtocolOutTopics(MatcherProtocolCommunicationServiceImpl.java:81) ~[bots.jar:na]
        at won.matcher.protocol.impl.MatcherProtocolMatcherServiceImplJMSBased.configureMatcherProtocolOutTopics(MatcherProtocolMatcherServiceImplJMSBased.java:81) ~[bots.jar:na]
        at won.matcher.protocol.impl.MatcherProtocolMatcherServiceImplJMSBased.access$000(MatcherProtocolMatcherServiceImplJMSBased.java:43) ~[bots.jar:na]
        at won.matcher.protocol.impl.MatcherProtocolMatcherServiceImplJMSBased$1.run(MatcherProtocolMatcherServiceImplJMSBased.java:95) ~[bots.jar:na]
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://node.matchat.org/won/resource":Read timed out; nested exception is java.net.SocketTimeoutException: Read timed out
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:584) ~[bots.jar:na]
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:544) ~[bots.jar:na]
        at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:465) ~[bots.jar:na]
        at won.protocol.rest.LinkedDataRestClient.readResourceData(LinkedDataRestClient.java:100) ~[bots.jar:na]
        ... 13 common frames omitted
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_111]
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_111]
        at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_111]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_111]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[na:1.8.0_111]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[na:1.8.0_111]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973) ~[na:1.8.0_111]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930) ~[na:1.8.0_111]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[na:1.8.0_111]
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:139) ~[bots.jar:na]
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:155) ~[bots.jar:na]
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:284) ~[bots.jar:na]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140) ~[bots.jar:na]
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57) ~[bots.jar:na]
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261) ~[bots.jar:na]
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165) ~[bots.jar:na]
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167) ~[bots.jar:na]
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272) ~[bots.jar:na]
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124) ~[bots.jar:na]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271) ~[bots.jar:na]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[bots.jar:na]
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88) ~[bots.jar:na]
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[bots.jar:na]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[bots.jar:na]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[bots.jar:na]
        at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91) ~[bots.jar:na]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[bots.jar:na]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[bots.jar:na]
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:568) ~[bots.jar:na]
        ... 16 common frames omitted
``

**Comment by heikofriedrich** [comment]
RegisterMatcherAction was only executed once by the bot and if that method fails registration is not tried again => changed this to retry registration in fixed time intervals in cause of failure
