### ISSUE TITLE
NullPointerException in debug bot on matchat

### ISSUE THREAD

**Issue by heikofriedrich** [researchstudio-sat/webofneeds#969]
3.2.17 16:13:35.185 [taskScheduler-15] ERROR w.p.m.p.i.SignatureAddingWonMessageProcessor - Failed to sign
java.lang.NullPointerException: null
        at won.cryptography.rdfsign.WonSigner.sign(WonSigner.java:87) ~[bots.jar:na]
        at won.cryptography.rdfsign.WonSigner.sign(WonSigner.java:118) ~[bots.jar:na]
        at won.protocol.message.processor.impl.WonMessageSignerVerifier.signContents(WonMessageSignerVerifier.java:112) ~[bots.jar:na]
        at won.protocol.message.processor.impl.WonMessageSignerVerifier.sign(WonMessageSignerVerifier.java:38) ~[bots.jar:na]
        at won.protocol.message.processor.impl.SignatureAddingWonMessageProcessor.processWithKey(SignatureAddingWonMessageProcessor.java:57) ~[bots.jar:na]
        at won.protocol.message.processor.impl.SignatureAddingWonMessageProcessor.processOnBehalfOfNeed(SignatureAddingWonMessageProcessor.java:48) ~[bots.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.doSigningOnOwner(OwnerWonMessageSenderJMSBased.java:122) [bots.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:74) [bots.jar:na]
        at won.bot.framework.bot.base.EventBot$EventGeneratingWonMessageSenderWrapper.sendWonMessage(EventBot.java:411) [bots.jar:na]
        at won.bot.framework.eventbot.action.impl.wonmessage.SendMessageOnConnectionAction.sendMessage(SendMessageOnConnectionAction.java:47) [bots.jar:na]
        at won.bot.framework.eventbot.action.impl.wonmessage.SendMessageOnConnectionAction.doRun(SendMessageOnConnectionAction.java:39) [bots.jar:na]
        at won.bot.framework.eventbot.action.BaseEventBotAction$1.run(BaseEventBotAction.java:56) [bots.jar:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [bots.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
3.2.17 16:13:35.186 [taskScheduler-15] WARN  w.b.f.e.a.i.w.SendMessageOnConnectionAction - could not send message via connection https://node.matchat.org/won/resource/connection/tlqeexoupyyrhmkkd8uj
java.lang.RuntimeException: could not send message
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:103) ~[bots.jar:na]
        at won.bot.framework.bot.base.EventBot$EventGeneratingWonMessageSenderWrapper.sendWonMessage(EventBot.java:411) ~[bots.jar:na]
        at won.bot.framework.eventbot.action.impl.wonmessage.SendMessageOnConnectionAction.sendMessage(SendMessageOnConnectionAction.java:47) [bots.jar:na]
        at won.bot.framework.eventbot.action.impl.wonmessage.SendMessageOnConnectionAction.doRun(SendMessageOnConnectionAction.java:39) [bots.jar:na]
        at won.bot.framework.eventbot.action.BaseEventBotAction$1.run(BaseEventBotAction.java:56) [bots.jar:na]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [bots.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
Caused by: won.protocol.message.processor.exception.WonMessageProcessingException: Failed to sign message https://node.matchat.org/won/resource/event/nw2fpn1pxjnyg7c0ernu
        at won.protocol.message.processor.impl.SignatureAddingWonMessageProcessor.processOnBehalfOfNeed(SignatureAddingWonMessageProcessor.java:51) ~[bots.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.doSigningOnOwner(OwnerWonMessageSenderJMSBased.java:122) ~[bots.jar:na]
        at won.owner.messaging.OwnerWonMessageSenderJMSBased.sendWonMessage(OwnerWonMessageSenderJMSBased.java:74) ~[bots.jar:na]
        ... 12 common frames omitted

**Comment by heikofriedrich** [comment]
In SignatureAddingWonMessageProcessor in method processOnBehalfOfNeed() it is not checked if public key is null. however at least exceptions are caught here
